/**
 * THIS FILE IS GENERATED by scripts/generate_agent_indexes.py
 * DO NOT EDIT BY HAND.
 */

export const latestSkillsIndex = {
  "schema_version": "x07.website.agent.skills_index@v1",
  "generated_from": "agent/latest/skills/*/SKILL.md",
  "items": [
    {
      "id": "x07-agent-playbook",
      "summary": "Agent-first workflow and design rails for building X07 programs with the released toolchain (no repo-only dependencies). Canonical execution is via `x07 run`.",
      "docs_url": "/agent/latest/skills/x07-agent-playbook/SKILL.md",
      "report_schema_url": null
    },
    {
      "id": "x07-build-run",
      "summary": "Expert backend for deterministic solve-world execution via x07-host-runner. Prefer `x07 run` as the canonical agent entry point.",
      "docs_url": "/agent/latest/skills/x07-build-run/SKILL.md",
      "report_schema_url": "/agent/latest/schemas/x07-host-runner.report.schema.json"
    },
    {
      "id": "x07-concurrency",
      "summary": "Canonical deterministic concurrency patterns in X07 (defasync + task.* + chan.bytes.*), including the determinism constraints.",
      "docs_url": "/agent/latest/skills/x07-concurrency/SKILL.md",
      "report_schema_url": null
    },
    {
      "id": "x07-ffi-c",
      "summary": "Emit C output and a C header for embedding X07 in C/C++ via `x07 build --emit-c-header`.",
      "docs_url": "/agent/latest/skills/x07-ffi-c/SKILL.md",
      "report_schema_url": null
    },
    {
      "id": "x07-format",
      "summary": "Canonically format X07 x07AST JSON files using `x07 fmt` (check/write) with a machine-readable JSON report.",
      "docs_url": "/agent/latest/skills/x07-format/SKILL.md",
      "report_schema_url": "/agent/latest/schemas/x07c.report.schema.json"
    },
    {
      "id": "x07-io-streams",
      "summary": "Canonical streaming I/O patterns in X07 using std.io / std.io.bufread and world adapters.",
      "docs_url": "/agent/latest/skills/x07-io-streams/SKILL.md",
      "report_schema_url": null
    },
    {
      "id": "x07-language-guide",
      "summary": "Canonical X07 language + stdlib reference (mirrors `x07 guide` output) for end-user skill packs.",
      "docs_url": "/agent/latest/skills/x07-language-guide/SKILL.md",
      "report_schema_url": null
    },
    {
      "id": "x07-lint-repair",
      "summary": "Lint X07 x07AST JSON and converge via deterministic quickfixes (`x07 fix`) or explicit JSON Patch (`x07 ast apply-patch`).",
      "docs_url": "/agent/latest/skills/x07-lint-repair/SKILL.md",
      "report_schema_url": "/agent/latest/schemas/x07c.report.schema.json"
    },
    {
      "id": "x07-os-run",
      "summary": "Expert backend for run-os / run-os-sandboxed execution via x07-os-runner. Prefer `x07 run --profile os` / `x07 run --profile sandbox`.",
      "docs_url": "/agent/latest/skills/x07-os-run/SKILL.md",
      "report_schema_url": "/agent/latest/schemas/x07-os-runner.report.schema.json"
    },
    {
      "id": "x07-package",
      "summary": "Manage X07 project dependencies and lockfiles for reproducible builds (lock, publish). Designed for autonomous agents.",
      "docs_url": "/agent/latest/skills/x07-package/SKILL.md",
      "report_schema_url": null
    },
    {
      "id": "x07-run",
      "summary": "Canonical execution front door for X07 programs (solve-* and run-os*), producing pass-through runner reports.",
      "docs_url": "/agent/latest/skills/x07-run/SKILL.md",
      "report_schema_url": null
    },
    {
      "id": "x07-test",
      "summary": "Run project tests using the X07 test harness (x07 test), producing a machine-readable JSON report.",
      "docs_url": "/agent/latest/skills/x07-test/SKILL.md",
      "report_schema_url": "/agent/latest/schemas/x07test.schema.json"
    }
  ]
} as const;

export const latestSchemasIndex = {
  "schema_version": "x07.website.agent.schemas_index@v1",
  "generated_from": "agent/latest/schemas/*.schema.json",
  "items": [
    {
      "id": "run-os-policy.schema.json",
      "url": "/agent/latest/schemas/run-os-policy.schema.json"
    },
    {
      "id": "x07-host-runner.report.schema.json",
      "url": "/agent/latest/schemas/x07-host-runner.report.schema.json"
    },
    {
      "id": "x07-install.channels.schema.json",
      "url": "/agent/latest/schemas/x07-install.channels.schema.json"
    },
    {
      "id": "x07-os-runner.report.schema.json",
      "url": "/agent/latest/schemas/x07-os-runner.report.schema.json"
    },
    {
      "id": "x07-policy-init.report.schema.json",
      "url": "/agent/latest/schemas/x07-policy-init.report.schema.json"
    },
    {
      "id": "x07-run.report.schema.json",
      "url": "/agent/latest/schemas/x07-run.report.schema.json"
    },
    {
      "id": "x07.native-backends.schema.json",
      "url": "/agent/latest/schemas/x07.native-backends.schema.json"
    },
    {
      "id": "x07.native-requires.schema.json",
      "url": "/agent/latest/schemas/x07.native-requires.schema.json"
    },
    {
      "id": "x07ast.schema.json",
      "url": "/agent/latest/schemas/x07ast.schema.json"
    },
    {
      "id": "x07c.report.schema.json",
      "url": "/agent/latest/schemas/x07c.report.schema.json"
    },
    {
      "id": "x07cli.specrows.schema.json",
      "url": "/agent/latest/schemas/x07cli.specrows.schema.json"
    },
    {
      "id": "x07diag.schema.json",
      "url": "/agent/latest/schemas/x07diag.schema.json"
    },
    {
      "id": "x07patch.schema.json",
      "url": "/agent/latest/schemas/x07patch.schema.json"
    },
    {
      "id": "x07test.schema.json",
      "url": "/agent/latest/schemas/x07test.schema.json"
    }
  ]
} as const;

export const latestExamplesIndex = {
  "schema_version": "x07.website.agent.examples_index@v1",
  "generated_from": "agent/latest/examples/*.x07.json",
  "items": [
    {
      "id": "01_echo",
      "purpose": "echo",
      "url": "/agent/latest/examples/01_echo.x07.json"
    },
    {
      "id": "02_length",
      "purpose": "length",
      "url": "/agent/latest/examples/02_length.x07.json"
    },
    {
      "id": "03_reverse",
      "purpose": "reverse",
      "url": "/agent/latest/examples/03_reverse.x07.json"
    },
    {
      "id": "04_sum_bytes",
      "purpose": "sum bytes",
      "url": "/agent/latest/examples/04_sum_bytes.x07.json"
    },
    {
      "id": "05_max_byte",
      "purpose": "max byte",
      "url": "/agent/latest/examples/05_max_byte.x07.json"
    },
    {
      "id": "06_count_first",
      "purpose": "count first",
      "url": "/agent/latest/examples/06_count_first.x07.json"
    },
    {
      "id": "07_first_line_len",
      "purpose": "first line len",
      "url": "/agent/latest/examples/07_first_line_len.x07.json"
    },
    {
      "id": "08_is_palindrome",
      "purpose": "is palindrome",
      "url": "/agent/latest/examples/08_is_palindrome.x07.json"
    },
    {
      "id": "09_word_count",
      "purpose": "word count",
      "url": "/agent/latest/examples/09_word_count.x07.json"
    },
    {
      "id": "10_rle_encode",
      "purpose": "rle encode",
      "url": "/agent/latest/examples/10_rle_encode.x07.json"
    },
    {
      "id": "11_data_analyzer",
      "purpose": "data analyzer",
      "url": "/agent/latest/examples/11_data_analyzer.x07.json"
    },
    {
      "id": "12_async_mapreduce",
      "purpose": "async mapreduce",
      "url": "/agent/latest/examples/12_async_mapreduce.x07.json"
    }
  ]
} as const;

export const latestPackagesIndex = {
  "schema_version": "x07.website.agent.packages_index@v1",
  "generated_from": "agent/latest/packages/*/*/index.json",
  "items": [
    {
      "name": "ext-aho-corasick-rs",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-aho-corasick-rs/0.1.0/index.json"
    },
    {
      "name": "ext-aho-corasick-rs",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-aho-corasick-rs/0.1.1/index.json"
    },
    {
      "name": "ext-aho-corasick-rs",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-aho-corasick-rs/0.1.2/index.json"
    },
    {
      "name": "ext-base64-rs",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-base64-rs/0.1.0/index.json"
    },
    {
      "name": "ext-base64-rs",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-base64-rs/0.1.1/index.json"
    },
    {
      "name": "ext-base64-rs",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-base64-rs/0.1.2/index.json"
    },
    {
      "name": "ext-byteorder-rs",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-byteorder-rs/0.1.0/index.json"
    },
    {
      "name": "ext-byteorder-rs",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-byteorder-rs/0.1.1/index.json"
    },
    {
      "name": "ext-byteorder-rs",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-byteorder-rs/0.1.2/index.json"
    },
    {
      "name": "ext-cli",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-cli/0.1.0/index.json"
    },
    {
      "name": "ext-cli",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-cli/0.1.1/index.json"
    },
    {
      "name": "ext-cli",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-cli/0.1.2/index.json"
    },
    {
      "name": "ext-cli",
      "version": "0.1.3",
      "url": "/agent/latest/packages/ext-cli/0.1.3/index.json"
    },
    {
      "name": "ext-compress-rs",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-compress-rs/0.1.0/index.json"
    },
    {
      "name": "ext-compress-rs",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-compress-rs/0.1.1/index.json"
    },
    {
      "name": "ext-compress-rs",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-compress-rs/0.1.2/index.json"
    },
    {
      "name": "ext-crypto-rs",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-crypto-rs/0.1.0/index.json"
    },
    {
      "name": "ext-crypto-rs",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-crypto-rs/0.1.1/index.json"
    },
    {
      "name": "ext-crypto-rs",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-crypto-rs/0.1.2/index.json"
    },
    {
      "name": "ext-csv-rs",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-csv-rs/0.1.0/index.json"
    },
    {
      "name": "ext-csv-rs",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-csv-rs/0.1.1/index.json"
    },
    {
      "name": "ext-csv-rs",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-csv-rs/0.1.2/index.json"
    },
    {
      "name": "ext-curl-c",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-curl-c/0.1.0/index.json"
    },
    {
      "name": "ext-curl-c",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-curl-c/0.1.1/index.json"
    },
    {
      "name": "ext-curl-c",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-curl-c/0.1.2/index.json"
    },
    {
      "name": "ext-curl-c",
      "version": "0.1.3",
      "url": "/agent/latest/packages/ext-curl-c/0.1.3/index.json"
    },
    {
      "name": "ext-data-model",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-data-model/0.1.0/index.json"
    },
    {
      "name": "ext-data-model",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-data-model/0.1.1/index.json"
    },
    {
      "name": "ext-data-model",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-data-model/0.1.2/index.json"
    },
    {
      "name": "ext-db-core",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-db-core/0.1.0/index.json"
    },
    {
      "name": "ext-db-core",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-db-core/0.1.1/index.json"
    },
    {
      "name": "ext-db-core",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-db-core/0.1.2/index.json"
    },
    {
      "name": "ext-db-mysql",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-db-mysql/0.1.0/index.json"
    },
    {
      "name": "ext-db-mysql",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-db-mysql/0.1.1/index.json"
    },
    {
      "name": "ext-db-mysql",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-db-mysql/0.1.2/index.json"
    },
    {
      "name": "ext-db-postgres",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-db-postgres/0.1.0/index.json"
    },
    {
      "name": "ext-db-postgres",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-db-postgres/0.1.1/index.json"
    },
    {
      "name": "ext-db-postgres",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-db-postgres/0.1.2/index.json"
    },
    {
      "name": "ext-db-redis",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-db-redis/0.1.0/index.json"
    },
    {
      "name": "ext-db-redis",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-db-redis/0.1.1/index.json"
    },
    {
      "name": "ext-db-redis",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-db-redis/0.1.2/index.json"
    },
    {
      "name": "ext-db-sqlite",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-db-sqlite/0.1.0/index.json"
    },
    {
      "name": "ext-db-sqlite",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-db-sqlite/0.1.1/index.json"
    },
    {
      "name": "ext-db-sqlite",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-db-sqlite/0.1.2/index.json"
    },
    {
      "name": "ext-error",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-error/0.1.0/index.json"
    },
    {
      "name": "ext-error",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-error/0.1.1/index.json"
    },
    {
      "name": "ext-error",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-error/0.1.2/index.json"
    },
    {
      "name": "ext-fs",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-fs/0.1.0/index.json"
    },
    {
      "name": "ext-fs",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-fs/0.1.1/index.json"
    },
    {
      "name": "ext-fs",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-fs/0.1.2/index.json"
    },
    {
      "name": "ext-hex-rs",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-hex-rs/0.1.0/index.json"
    },
    {
      "name": "ext-hex-rs",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-hex-rs/0.1.1/index.json"
    },
    {
      "name": "ext-hex-rs",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-hex-rs/0.1.2/index.json"
    },
    {
      "name": "ext-ini-rs",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-ini-rs/0.1.0/index.json"
    },
    {
      "name": "ext-ini-rs",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-ini-rs/0.1.1/index.json"
    },
    {
      "name": "ext-ini-rs",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-ini-rs/0.1.2/index.json"
    },
    {
      "name": "ext-json-rs",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-json-rs/0.1.0/index.json"
    },
    {
      "name": "ext-json-rs",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-json-rs/0.1.1/index.json"
    },
    {
      "name": "ext-json-rs",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-json-rs/0.1.2/index.json"
    },
    {
      "name": "ext-log",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-log/0.1.0/index.json"
    },
    {
      "name": "ext-log",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-log/0.1.1/index.json"
    },
    {
      "name": "ext-log",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-log/0.1.2/index.json"
    },
    {
      "name": "ext-math",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-math/0.1.0/index.json"
    },
    {
      "name": "ext-math",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-math/0.1.1/index.json"
    },
    {
      "name": "ext-math",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-math/0.1.2/index.json"
    },
    {
      "name": "ext-memchr-rs",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-memchr-rs/0.1.0/index.json"
    },
    {
      "name": "ext-memchr-rs",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-memchr-rs/0.1.1/index.json"
    },
    {
      "name": "ext-memchr-rs",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-memchr-rs/0.1.2/index.json"
    },
    {
      "name": "ext-net",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-net/0.1.0/index.json"
    },
    {
      "name": "ext-net",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-net/0.1.1/index.json"
    },
    {
      "name": "ext-net",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-net/0.1.2/index.json"
    },
    {
      "name": "ext-openssl-c",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-openssl-c/0.1.0/index.json"
    },
    {
      "name": "ext-openssl-c",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-openssl-c/0.1.1/index.json"
    },
    {
      "name": "ext-openssl-c",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-openssl-c/0.1.2/index.json"
    },
    {
      "name": "ext-openssl-c",
      "version": "0.1.3",
      "url": "/agent/latest/packages/ext-openssl-c/0.1.3/index.json"
    },
    {
      "name": "ext-pb-rs",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-pb-rs/0.1.0/index.json"
    },
    {
      "name": "ext-pb-rs",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-pb-rs/0.1.1/index.json"
    },
    {
      "name": "ext-pb-rs",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-pb-rs/0.1.2/index.json"
    },
    {
      "name": "ext-regex",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-regex/0.1.0/index.json"
    },
    {
      "name": "ext-regex",
      "version": "0.2.0",
      "url": "/agent/latest/packages/ext-regex/0.2.0/index.json"
    },
    {
      "name": "ext-regex",
      "version": "0.2.1",
      "url": "/agent/latest/packages/ext-regex/0.2.1/index.json"
    },
    {
      "name": "ext-regex",
      "version": "0.2.2",
      "url": "/agent/latest/packages/ext-regex/0.2.2/index.json"
    },
    {
      "name": "ext-semver-rs",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-semver-rs/0.1.0/index.json"
    },
    {
      "name": "ext-semver-rs",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-semver-rs/0.1.1/index.json"
    },
    {
      "name": "ext-semver-rs",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-semver-rs/0.1.2/index.json"
    },
    {
      "name": "ext-sockets-c",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-sockets-c/0.1.0/index.json"
    },
    {
      "name": "ext-sockets-c",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-sockets-c/0.1.1/index.json"
    },
    {
      "name": "ext-sockets-c",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-sockets-c/0.1.2/index.json"
    },
    {
      "name": "ext-sockets-c",
      "version": "0.1.3",
      "url": "/agent/latest/packages/ext-sockets-c/0.1.3/index.json"
    },
    {
      "name": "ext-streams",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-streams/0.1.0/index.json"
    },
    {
      "name": "ext-streams",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-streams/0.1.1/index.json"
    },
    {
      "name": "ext-streams",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-streams/0.1.2/index.json"
    },
    {
      "name": "ext-tar-rs",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-tar-rs/0.1.0/index.json"
    },
    {
      "name": "ext-tar-rs",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-tar-rs/0.1.1/index.json"
    },
    {
      "name": "ext-tar-rs",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-tar-rs/0.1.2/index.json"
    },
    {
      "name": "ext-time-rs",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-time-rs/0.1.0/index.json"
    },
    {
      "name": "ext-time-rs",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-time-rs/0.1.1/index.json"
    },
    {
      "name": "ext-time-rs",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-time-rs/0.1.2/index.json"
    },
    {
      "name": "ext-toml-rs",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-toml-rs/0.1.0/index.json"
    },
    {
      "name": "ext-toml-rs",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-toml-rs/0.1.1/index.json"
    },
    {
      "name": "ext-toml-rs",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-toml-rs/0.1.2/index.json"
    },
    {
      "name": "ext-tracing",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-tracing/0.1.0/index.json"
    },
    {
      "name": "ext-tracing",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-tracing/0.1.1/index.json"
    },
    {
      "name": "ext-tracing",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-tracing/0.1.2/index.json"
    },
    {
      "name": "ext-u64-rs",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-u64-rs/0.1.0/index.json"
    },
    {
      "name": "ext-u64-rs",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-u64-rs/0.1.1/index.json"
    },
    {
      "name": "ext-u64-rs",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-u64-rs/0.1.2/index.json"
    },
    {
      "name": "ext-unicode-rs",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-unicode-rs/0.1.0/index.json"
    },
    {
      "name": "ext-unicode-rs",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-unicode-rs/0.1.1/index.json"
    },
    {
      "name": "ext-unicode-rs",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-unicode-rs/0.1.2/index.json"
    },
    {
      "name": "ext-url-rs",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-url-rs/0.1.0/index.json"
    },
    {
      "name": "ext-url-rs",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-url-rs/0.1.1/index.json"
    },
    {
      "name": "ext-url-rs",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-url-rs/0.1.2/index.json"
    },
    {
      "name": "ext-uuid-rs",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-uuid-rs/0.1.0/index.json"
    },
    {
      "name": "ext-uuid-rs",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-uuid-rs/0.1.1/index.json"
    },
    {
      "name": "ext-uuid-rs",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-uuid-rs/0.1.2/index.json"
    },
    {
      "name": "ext-xml-rs",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-xml-rs/0.1.0/index.json"
    },
    {
      "name": "ext-xml-rs",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-xml-rs/0.1.1/index.json"
    },
    {
      "name": "ext-xml-rs",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-xml-rs/0.1.2/index.json"
    },
    {
      "name": "ext-yaml-rs",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-yaml-rs/0.1.0/index.json"
    },
    {
      "name": "ext-yaml-rs",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-yaml-rs/0.1.1/index.json"
    },
    {
      "name": "ext-yaml-rs",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-yaml-rs/0.1.2/index.json"
    },
    {
      "name": "ext-zlib-c",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-zlib-c/0.1.0/index.json"
    },
    {
      "name": "ext-zlib-c",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-zlib-c/0.1.1/index.json"
    },
    {
      "name": "ext-zlib-c",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-zlib-c/0.1.2/index.json"
    },
    {
      "name": "ext-zlib-c",
      "version": "0.1.3",
      "url": "/agent/latest/packages/ext-zlib-c/0.1.3/index.json"
    }
  ]
} as const;

export const latestStdlibIndexMeta = {
  url: '/agent/latest/stdlib/index.json',
  module_count: 39,
} as const;
