/**
 * THIS FILE IS GENERATED by scripts/generate_agent_indexes.py
 * DO NOT EDIT BY HAND.
 */

export const latestSkillsIndex = {
  "schema_version": "x07.website.agent.skills_index@v1",
  "generated_from": "agent/latest/skills/*/SKILL.md",
  "items": [
    {
      "id": "x07-agent-playbook",
      "summary": "Agent-first workflow and design rails for building X07 programs with the released toolchain (no repo-only dependencies). Canonical execution is via `x07 run`.",
      "docs_url": "/agent/latest/skills/x07-agent-playbook/SKILL.md",
      "report_schema_url": null
    },
    {
      "id": "x07-bundle",
      "summary": "Produce distributable native executables (normal CLI ABI) via `x07 bundle`.",
      "docs_url": "/agent/latest/skills/x07-bundle/SKILL.md",
      "report_schema_url": null
    },
    {
      "id": "x07-concurrency",
      "summary": "Canonical concurrency patterns in X07 (defasync + task.* + chan.bytes.*), including sandbox constraints.",
      "docs_url": "/agent/latest/skills/x07-concurrency/SKILL.md",
      "report_schema_url": null
    },
    {
      "id": "x07-ffi-c",
      "summary": "Emit C output and a C header for embedding X07 in C/C++ via `x07 build --emit-c-header`.",
      "docs_url": "/agent/latest/skills/x07-ffi-c/SKILL.md",
      "report_schema_url": null
    },
    {
      "id": "x07-format",
      "summary": "Canonically format X07 x07AST JSON files using `x07 fmt` (check/write) with a machine-readable JSON report.",
      "docs_url": "/agent/latest/skills/x07-format/SKILL.md",
      "report_schema_url": "/agent/latest/schemas/x07c.report.schema.json"
    },
    {
      "id": "x07-io-streams",
      "summary": "Canonical streaming I/O patterns in X07 using std.io / std.io.bufread and world adapters.",
      "docs_url": "/agent/latest/skills/x07-io-streams/SKILL.md",
      "report_schema_url": null
    },
    {
      "id": "x07-language-guide",
      "summary": "Canonical X07 language + stdlib reference (mirrors `x07 guide` output) for end-user skill packs.",
      "docs_url": "/agent/latest/skills/x07-language-guide/SKILL.md",
      "report_schema_url": null
    },
    {
      "id": "x07-lint-repair",
      "summary": "Lint X07 x07AST JSON and converge via quickfixes (`x07 fix`) or explicit JSON Patch (`x07 ast apply-patch`).",
      "docs_url": "/agent/latest/skills/x07-lint-repair/SKILL.md",
      "report_schema_url": "/agent/latest/schemas/x07c.report.schema.json"
    },
    {
      "id": "x07-os-run",
      "summary": "Expert backend for run-os / run-os-sandboxed execution via x07-os-runner. Prefer `x07 run --profile os` / `x07 run --profile sandbox`.",
      "docs_url": "/agent/latest/skills/x07-os-run/SKILL.md",
      "report_schema_url": "/agent/latest/schemas/x07-os-runner.report.schema.json"
    },
    {
      "id": "x07-package",
      "summary": "Manage X07 project dependencies and lockfiles for reproducible builds (lock, publish). Designed for autonomous agents.",
      "docs_url": "/agent/latest/skills/x07-package/SKILL.md",
      "report_schema_url": null
    },
    {
      "id": "x07-run",
      "summary": "Canonical execution front door for X07 programs (run-os / run-os-sandboxed), producing runner reports.",
      "docs_url": "/agent/latest/skills/x07-run/SKILL.md",
      "report_schema_url": null
    },
    {
      "id": "x07-test",
      "summary": "Run project tests using the X07 test harness (x07 test), producing a machine-readable JSON report.",
      "docs_url": "/agent/latest/skills/x07-test/SKILL.md",
      "report_schema_url": "/agent/latest/schemas/x07test.schema.json"
    }
  ]
} as const;

export const latestSchemasIndex = {
  "schema_version": "x07.website.agent.schemas_index@v1",
  "generated_from": "agent/latest/schemas/*.schema.json",
  "items": [
    {
      "id": "run-os-policy.schema.json",
      "url": "/agent/latest/schemas/run-os-policy.schema.json"
    },
    {
      "id": "x07-arch.budgets.index.schema.json",
      "url": "/agent/latest/schemas/x07-arch.budgets.index.schema.json"
    },
    {
      "id": "x07-arch.contracts.lock.schema.json",
      "url": "/agent/latest/schemas/x07-arch.contracts.lock.schema.json"
    },
    {
      "id": "x07-arch.manifest.lock.schema.json",
      "url": "/agent/latest/schemas/x07-arch.manifest.lock.schema.json"
    },
    {
      "id": "x07-arch.manifest.schema.json",
      "url": "/agent/latest/schemas/x07-arch.manifest.schema.json"
    },
    {
      "id": "x07-arch.patchset.schema.json",
      "url": "/agent/latest/schemas/x07-arch.patchset.schema.json"
    },
    {
      "id": "x07-arch.report.schema.json",
      "url": "/agent/latest/schemas/x07-arch.report.schema.json"
    },
    {
      "id": "x07-arch.rr.index.schema.json",
      "url": "/agent/latest/schemas/x07-arch.rr.index.schema.json"
    },
    {
      "id": "x07-arch.rr.policy.schema.json",
      "url": "/agent/latest/schemas/x07-arch.rr.policy.schema.json"
    },
    {
      "id": "x07-arch.rr.sanitize.schema.json",
      "url": "/agent/latest/schemas/x07-arch.rr.sanitize.schema.json"
    },
    {
      "id": "x07-arch.sm.index.schema.json",
      "url": "/agent/latest/schemas/x07-arch.sm.index.schema.json"
    },
    {
      "id": "x07-arch.stream-plugin.schema.json",
      "url": "/agent/latest/schemas/x07-arch.stream-plugin.schema.json"
    },
    {
      "id": "x07-arch.stream-plugins.index.schema.json",
      "url": "/agent/latest/schemas/x07-arch.stream-plugins.index.schema.json"
    },
    {
      "id": "x07-budget.profile.schema.json",
      "url": "/agent/latest/schemas/x07-budget.profile.schema.json"
    },
    {
      "id": "x07-bundle.report.schema.json",
      "url": "/agent/latest/schemas/x07-bundle.report.schema.json"
    },
    {
      "id": "x07-capabilities.schema.json",
      "url": "/agent/latest/schemas/x07-capabilities.schema.json"
    },
    {
      "id": "x07-host-runner.report.schema.json",
      "url": "/agent/latest/schemas/x07-host-runner.report.schema.json"
    },
    {
      "id": "x07-install.channels.schema.json",
      "url": "/agent/latest/schemas/x07-install.channels.schema.json"
    },
    {
      "id": "x07-lock.schema.json",
      "url": "/agent/latest/schemas/x07-lock.schema.json"
    },
    {
      "id": "x07-os-runner.report.schema.json",
      "url": "/agent/latest/schemas/x07-os-runner.report.schema.json"
    },
    {
      "id": "x07-package.schema.json",
      "url": "/agent/latest/schemas/x07-package.schema.json"
    },
    {
      "id": "x07-policy-init.report.schema.json",
      "url": "/agent/latest/schemas/x07-policy-init.report.schema.json"
    },
    {
      "id": "x07-project.schema.json",
      "url": "/agent/latest/schemas/x07-project.schema.json"
    },
    {
      "id": "x07-run.report.schema.json",
      "url": "/agent/latest/schemas/x07-run.report.schema.json"
    },
    {
      "id": "x07-sm.spec.schema.json",
      "url": "/agent/latest/schemas/x07-sm.spec.schema.json"
    },
    {
      "id": "x07-website.package-index.schema.json",
      "url": "/agent/latest/schemas/x07-website.package-index.schema.json"
    },
    {
      "id": "x07.native-backends.schema.json",
      "url": "/agent/latest/schemas/x07.native-backends.schema.json"
    },
    {
      "id": "x07.native-requires.schema.json",
      "url": "/agent/latest/schemas/x07.native-requires.schema.json"
    },
    {
      "id": "x07ast.schema.json",
      "url": "/agent/latest/schemas/x07ast.schema.json"
    },
    {
      "id": "x07c.report.schema.json",
      "url": "/agent/latest/schemas/x07c.report.schema.json"
    },
    {
      "id": "x07cli.specrows.schema.json",
      "url": "/agent/latest/schemas/x07cli.specrows.schema.json"
    },
    {
      "id": "x07diag.schema.json",
      "url": "/agent/latest/schemas/x07diag.schema.json"
    },
    {
      "id": "x07patch.schema.json",
      "url": "/agent/latest/schemas/x07patch.schema.json"
    },
    {
      "id": "x07test.schema.json",
      "url": "/agent/latest/schemas/x07test.schema.json"
    }
  ]
} as const;

export const latestExamplesIndex = {
  "schema_version": "x07.website.agent.examples_index@v1",
  "generated_from": "agent/latest/examples/*.x07.json",
  "items": [
    {
      "id": "01_echo",
      "purpose": "echo",
      "url": "/agent/latest/examples/01_echo.x07.json"
    },
    {
      "id": "02_length",
      "purpose": "length",
      "url": "/agent/latest/examples/02_length.x07.json"
    },
    {
      "id": "03_reverse",
      "purpose": "reverse",
      "url": "/agent/latest/examples/03_reverse.x07.json"
    },
    {
      "id": "04_sum_bytes",
      "purpose": "sum bytes",
      "url": "/agent/latest/examples/04_sum_bytes.x07.json"
    },
    {
      "id": "05_max_byte",
      "purpose": "max byte",
      "url": "/agent/latest/examples/05_max_byte.x07.json"
    },
    {
      "id": "06_count_first",
      "purpose": "count first",
      "url": "/agent/latest/examples/06_count_first.x07.json"
    },
    {
      "id": "07_first_line_len",
      "purpose": "first line len",
      "url": "/agent/latest/examples/07_first_line_len.x07.json"
    },
    {
      "id": "08_is_palindrome",
      "purpose": "is palindrome",
      "url": "/agent/latest/examples/08_is_palindrome.x07.json"
    },
    {
      "id": "09_word_count",
      "purpose": "word count",
      "url": "/agent/latest/examples/09_word_count.x07.json"
    },
    {
      "id": "10_rle_encode",
      "purpose": "rle encode",
      "url": "/agent/latest/examples/10_rle_encode.x07.json"
    },
    {
      "id": "11_data_analyzer",
      "purpose": "data analyzer",
      "url": "/agent/latest/examples/11_data_analyzer.x07.json"
    },
    {
      "id": "12_async_mapreduce",
      "purpose": "async mapreduce",
      "url": "/agent/latest/examples/12_async_mapreduce.x07.json"
    },
    {
      "id": "13_stream_pipe_split_lines",
      "purpose": "stream pipe split lines",
      "url": "/agent/latest/examples/13_stream_pipe_split_lines.x07.json"
    },
    {
      "id": "14_task_scope_slots",
      "purpose": "task scope slots",
      "url": "/agent/latest/examples/14_task_scope_slots.x07.json"
    }
  ]
} as const;

export const latestPackagesIndex = {
  "schema_version": "x07.website.agent.packages_index@v1",
  "generated_from": "agent/latest/packages/*/*/index.json",
  "items": [
    {
      "name": "ext-aho-corasick-rs",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-aho-corasick-rs/0.1.0/index.json",
      "description": "",
      "docs_url": "/agent/latest/packages/ext-aho-corasick-rs/0.1.0/index.json#docs"
    },
    {
      "name": "ext-aho-corasick-rs",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-aho-corasick-rs/0.1.1/index.json",
      "description": "Aho\u2013Corasick multi-pattern substring search.",
      "docs_url": "/agent/latest/packages/ext-aho-corasick-rs/0.1.1/index.json#docs"
    },
    {
      "name": "ext-aho-corasick-rs",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-aho-corasick-rs/0.1.2/index.json",
      "description": "Aho\u2013Corasick multi-pattern substring search.",
      "docs_url": "/agent/latest/packages/ext-aho-corasick-rs/0.1.2/index.json#docs"
    },
    {
      "name": "ext-aho-corasick-rs",
      "version": "0.1.3",
      "url": "/agent/latest/packages/ext-aho-corasick-rs/0.1.3/index.json",
      "description": "Aho\u2013Corasick multi-pattern substring search.",
      "docs_url": "/agent/latest/packages/ext-aho-corasick-rs/0.1.3/index.json#docs"
    },
    {
      "name": "ext-aho-corasick-rs",
      "version": "0.1.4",
      "url": "/agent/latest/packages/ext-aho-corasick-rs/0.1.4/index.json",
      "description": "Aho\u2013Corasick multi-pattern substring search.",
      "docs_url": "/agent/latest/packages/ext-aho-corasick-rs/0.1.4/index.json#docs"
    },
    {
      "name": "ext-base64-rs",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-base64-rs/0.1.0/index.json",
      "description": "",
      "docs_url": "/agent/latest/packages/ext-base64-rs/0.1.0/index.json#docs"
    },
    {
      "name": "ext-base64-rs",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-base64-rs/0.1.1/index.json",
      "description": "Base64 encoding and decoding.",
      "docs_url": "/agent/latest/packages/ext-base64-rs/0.1.1/index.json#docs"
    },
    {
      "name": "ext-base64-rs",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-base64-rs/0.1.2/index.json",
      "description": "Base64 encoding and decoding.",
      "docs_url": "/agent/latest/packages/ext-base64-rs/0.1.2/index.json#docs"
    },
    {
      "name": "ext-base64-rs",
      "version": "0.1.3",
      "url": "/agent/latest/packages/ext-base64-rs/0.1.3/index.json",
      "description": "Base64 encoding and decoding.",
      "docs_url": "/agent/latest/packages/ext-base64-rs/0.1.3/index.json#docs"
    },
    {
      "name": "ext-base64-rs",
      "version": "0.1.4",
      "url": "/agent/latest/packages/ext-base64-rs/0.1.4/index.json",
      "description": "Base64 encoding and decoding.",
      "docs_url": "/agent/latest/packages/ext-base64-rs/0.1.4/index.json#docs"
    },
    {
      "name": "ext-bigint-rs",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-bigint-rs/0.1.0/index.json",
      "description": "Big integer utilities (codec_v1, parse, format, basic ops).",
      "docs_url": "/agent/latest/packages/ext-bigint-rs/0.1.0/index.json#docs"
    },
    {
      "name": "ext-bigint-rs",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-bigint-rs/0.1.1/index.json",
      "description": "Big integer utilities (codec_v1, parse, format, basic ops).",
      "docs_url": "/agent/latest/packages/ext-bigint-rs/0.1.1/index.json#docs"
    },
    {
      "name": "ext-bigint-rs",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-bigint-rs/0.1.2/index.json",
      "description": "Big integer utilities (codec_v1, parse, format, basic ops).",
      "docs_url": "/agent/latest/packages/ext-bigint-rs/0.1.2/index.json#docs"
    },
    {
      "name": "ext-byteorder-rs",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-byteorder-rs/0.1.0/index.json",
      "description": "",
      "docs_url": "/agent/latest/packages/ext-byteorder-rs/0.1.0/index.json#docs"
    },
    {
      "name": "ext-byteorder-rs",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-byteorder-rs/0.1.1/index.json",
      "description": "Endian-aware integer encoding and decoding.",
      "docs_url": "/agent/latest/packages/ext-byteorder-rs/0.1.1/index.json#docs"
    },
    {
      "name": "ext-byteorder-rs",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-byteorder-rs/0.1.2/index.json",
      "description": "Endian-aware integer encoding and decoding.",
      "docs_url": "/agent/latest/packages/ext-byteorder-rs/0.1.2/index.json#docs"
    },
    {
      "name": "ext-byteorder-rs",
      "version": "0.1.3",
      "url": "/agent/latest/packages/ext-byteorder-rs/0.1.3/index.json",
      "description": "Endian-aware integer encoding and decoding.",
      "docs_url": "/agent/latest/packages/ext-byteorder-rs/0.1.3/index.json#docs"
    },
    {
      "name": "ext-byteorder-rs",
      "version": "0.1.4",
      "url": "/agent/latest/packages/ext-byteorder-rs/0.1.4/index.json",
      "description": "Endian-aware integer encoding and decoding.",
      "docs_url": "/agent/latest/packages/ext-byteorder-rs/0.1.4/index.json#docs"
    },
    {
      "name": "ext-cbor-rs",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-cbor-rs/0.1.0/index.json",
      "description": "CBOR encode/decode with ext.data_model integration.",
      "docs_url": "/agent/latest/packages/ext-cbor-rs/0.1.0/index.json#docs"
    },
    {
      "name": "ext-cbor-rs",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-cbor-rs/0.1.1/index.json",
      "description": "CBOR encode/decode with ext.data_model integration.",
      "docs_url": "/agent/latest/packages/ext-cbor-rs/0.1.1/index.json#docs"
    },
    {
      "name": "ext-cbor-rs",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-cbor-rs/0.1.2/index.json",
      "description": "CBOR encode/decode with ext.data_model integration.",
      "docs_url": "/agent/latest/packages/ext-cbor-rs/0.1.2/index.json#docs"
    },
    {
      "name": "ext-cbor-rs",
      "version": "0.1.3",
      "url": "/agent/latest/packages/ext-cbor-rs/0.1.3/index.json",
      "description": "CBOR encode/decode with ext.data_model integration.",
      "docs_url": "/agent/latest/packages/ext-cbor-rs/0.1.3/index.json#docs"
    },
    {
      "name": "ext-cbor-rs",
      "version": "0.1.4",
      "url": "/agent/latest/packages/ext-cbor-rs/0.1.4/index.json",
      "description": "CBOR encode/decode with ext.data_model integration.",
      "docs_url": "/agent/latest/packages/ext-cbor-rs/0.1.4/index.json#docs"
    },
    {
      "name": "ext-cbor-rs",
      "version": "0.1.5",
      "url": "/agent/latest/packages/ext-cbor-rs/0.1.5/index.json",
      "description": "CBOR encode/decode with ext.data_model integration.",
      "docs_url": "/agent/latest/packages/ext-cbor-rs/0.1.5/index.json#docs"
    },
    {
      "name": "ext-checksum-rs",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-checksum-rs/0.1.0/index.json",
      "description": "Fast non-cryptographic checksums (CRC32C, xxhash64).",
      "docs_url": "/agent/latest/packages/ext-checksum-rs/0.1.0/index.json#docs"
    },
    {
      "name": "ext-checksum-rs",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-checksum-rs/0.1.1/index.json",
      "description": "Fast non-cryptographic checksums (CRC32C, xxhash64).",
      "docs_url": "/agent/latest/packages/ext-checksum-rs/0.1.1/index.json#docs"
    },
    {
      "name": "ext-checksum-rs",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-checksum-rs/0.1.2/index.json",
      "description": "Fast non-cryptographic checksums (CRC32C, xxhash64).",
      "docs_url": "/agent/latest/packages/ext-checksum-rs/0.1.2/index.json#docs"
    },
    {
      "name": "ext-cli",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-cli/0.1.0/index.json",
      "description": "",
      "docs_url": "/agent/latest/packages/ext-cli/0.1.0/index.json#docs"
    },
    {
      "name": "ext-cli",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-cli/0.1.1/index.json",
      "description": "Command-line argument parsing, help, and shell completion.",
      "docs_url": "/agent/latest/packages/ext-cli/0.1.1/index.json#docs"
    },
    {
      "name": "ext-cli",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-cli/0.1.2/index.json",
      "description": "Command-line argument parsing, help, and shell completion.",
      "docs_url": "/agent/latest/packages/ext-cli/0.1.2/index.json#docs"
    },
    {
      "name": "ext-cli",
      "version": "0.1.3",
      "url": "/agent/latest/packages/ext-cli/0.1.3/index.json",
      "description": "Command-line argument parsing, help, and shell completion.",
      "docs_url": "/agent/latest/packages/ext-cli/0.1.3/index.json#docs"
    },
    {
      "name": "ext-cli",
      "version": "0.1.4",
      "url": "/agent/latest/packages/ext-cli/0.1.4/index.json",
      "description": "Command-line argument parsing, help, and shell completion.",
      "docs_url": "/agent/latest/packages/ext-cli/0.1.4/index.json#docs"
    },
    {
      "name": "ext-cli",
      "version": "0.1.5",
      "url": "/agent/latest/packages/ext-cli/0.1.5/index.json",
      "description": "Command-line argument parsing, help, and shell completion.",
      "docs_url": "/agent/latest/packages/ext-cli/0.1.5/index.json#docs"
    },
    {
      "name": "ext-cli",
      "version": "0.1.6",
      "url": "/agent/latest/packages/ext-cli/0.1.6/index.json",
      "description": "Command-line argument parsing, help, and shell completion.",
      "docs_url": "/agent/latest/packages/ext-cli/0.1.6/index.json#docs"
    },
    {
      "name": "ext-cli",
      "version": "0.1.7",
      "url": "/agent/latest/packages/ext-cli/0.1.7/index.json",
      "description": "Command-line argument parsing, help, and shell completion.",
      "docs_url": "/agent/latest/packages/ext-cli/0.1.7/index.json#docs"
    },
    {
      "name": "ext-cli",
      "version": "0.1.8",
      "url": "/agent/latest/packages/ext-cli/0.1.8/index.json",
      "description": "Command-line argument parsing, help, and shell completion.",
      "docs_url": "/agent/latest/packages/ext-cli/0.1.8/index.json#docs"
    },
    {
      "name": "ext-cli",
      "version": "0.1.9",
      "url": "/agent/latest/packages/ext-cli/0.1.9/index.json",
      "description": "Command-line argument parsing, help, and shell completion.",
      "docs_url": "/agent/latest/packages/ext-cli/0.1.9/index.json#docs"
    },
    {
      "name": "ext-cli",
      "version": "0.1.10",
      "url": "/agent/latest/packages/ext-cli/0.1.10/index.json",
      "description": "Command-line argument parsing, help, and shell completion.",
      "docs_url": "/agent/latest/packages/ext-cli/0.1.10/index.json#docs"
    },
    {
      "name": "ext-compress-rs",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-compress-rs/0.1.0/index.json",
      "description": "",
      "docs_url": "/agent/latest/packages/ext-compress-rs/0.1.0/index.json#docs"
    },
    {
      "name": "ext-compress-rs",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-compress-rs/0.1.1/index.json",
      "description": "Compression primitives and ZIP archives.",
      "docs_url": "/agent/latest/packages/ext-compress-rs/0.1.1/index.json#docs"
    },
    {
      "name": "ext-compress-rs",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-compress-rs/0.1.2/index.json",
      "description": "Compression primitives and ZIP archives.",
      "docs_url": "/agent/latest/packages/ext-compress-rs/0.1.2/index.json#docs"
    },
    {
      "name": "ext-compress-rs",
      "version": "0.1.3",
      "url": "/agent/latest/packages/ext-compress-rs/0.1.3/index.json",
      "description": "Compression primitives and ZIP archives.",
      "docs_url": "/agent/latest/packages/ext-compress-rs/0.1.3/index.json#docs"
    },
    {
      "name": "ext-compress-rs",
      "version": "0.1.4",
      "url": "/agent/latest/packages/ext-compress-rs/0.1.4/index.json",
      "description": "Compression primitives and ZIP archives.",
      "docs_url": "/agent/latest/packages/ext-compress-rs/0.1.4/index.json#docs"
    },
    {
      "name": "ext-compress-rs",
      "version": "0.1.5",
      "url": "/agent/latest/packages/ext-compress-rs/0.1.5/index.json",
      "description": "Compression primitives and ZIP archives.",
      "docs_url": "/agent/latest/packages/ext-compress-rs/0.1.5/index.json#docs"
    },
    {
      "name": "ext-crypto-rs",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-crypto-rs/0.1.0/index.json",
      "description": "",
      "docs_url": "/agent/latest/packages/ext-crypto-rs/0.1.0/index.json#docs"
    },
    {
      "name": "ext-crypto-rs",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-crypto-rs/0.1.1/index.json",
      "description": "SHA-256/SHA-512, HMAC-SHA256, and HKDF-SHA256 utilities.",
      "docs_url": "/agent/latest/packages/ext-crypto-rs/0.1.1/index.json#docs"
    },
    {
      "name": "ext-crypto-rs",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-crypto-rs/0.1.2/index.json",
      "description": "SHA-256/SHA-512, HMAC-SHA256, and HKDF-SHA256 utilities.",
      "docs_url": "/agent/latest/packages/ext-crypto-rs/0.1.2/index.json#docs"
    },
    {
      "name": "ext-crypto-rs",
      "version": "0.1.3",
      "url": "/agent/latest/packages/ext-crypto-rs/0.1.3/index.json",
      "description": "SHA-256/SHA-512, HMAC-SHA256, and HKDF-SHA256 utilities.",
      "docs_url": "/agent/latest/packages/ext-crypto-rs/0.1.3/index.json#docs"
    },
    {
      "name": "ext-crypto-rs",
      "version": "0.1.4",
      "url": "/agent/latest/packages/ext-crypto-rs/0.1.4/index.json",
      "description": "SHA-256/SHA-512, HMAC-SHA256, and HKDF-SHA256 utilities.",
      "docs_url": "/agent/latest/packages/ext-crypto-rs/0.1.4/index.json#docs"
    },
    {
      "name": "ext-csv-rs",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-csv-rs/0.1.0/index.json",
      "description": "",
      "docs_url": "/agent/latest/packages/ext-csv-rs/0.1.0/index.json#docs"
    },
    {
      "name": "ext-csv-rs",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-csv-rs/0.1.1/index.json",
      "description": "CSV parsing and writing.",
      "docs_url": "/agent/latest/packages/ext-csv-rs/0.1.1/index.json#docs"
    },
    {
      "name": "ext-csv-rs",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-csv-rs/0.1.2/index.json",
      "description": "CSV parsing and writing.",
      "docs_url": "/agent/latest/packages/ext-csv-rs/0.1.2/index.json#docs"
    },
    {
      "name": "ext-csv-rs",
      "version": "0.1.3",
      "url": "/agent/latest/packages/ext-csv-rs/0.1.3/index.json",
      "description": "CSV parsing and writing.",
      "docs_url": "/agent/latest/packages/ext-csv-rs/0.1.3/index.json#docs"
    },
    {
      "name": "ext-csv-rs",
      "version": "0.1.4",
      "url": "/agent/latest/packages/ext-csv-rs/0.1.4/index.json",
      "description": "CSV parsing and writing.",
      "docs_url": "/agent/latest/packages/ext-csv-rs/0.1.4/index.json#docs"
    },
    {
      "name": "ext-curl-c",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-curl-c/0.1.0/index.json",
      "description": "",
      "docs_url": "/agent/latest/packages/ext-curl-c/0.1.0/index.json#docs"
    },
    {
      "name": "ext-curl-c",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-curl-c/0.1.1/index.json",
      "description": "HTTP(S) client bindings via libcurl (run-os only).",
      "docs_url": "/agent/latest/packages/ext-curl-c/0.1.1/index.json#docs"
    },
    {
      "name": "ext-curl-c",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-curl-c/0.1.2/index.json",
      "description": "HTTP(S) client bindings via libcurl (run-os only).",
      "docs_url": "/agent/latest/packages/ext-curl-c/0.1.2/index.json#docs"
    },
    {
      "name": "ext-curl-c",
      "version": "0.1.3",
      "url": "/agent/latest/packages/ext-curl-c/0.1.3/index.json",
      "description": "HTTP(S) client bindings via libcurl (run-os only).",
      "docs_url": "/agent/latest/packages/ext-curl-c/0.1.3/index.json#docs"
    },
    {
      "name": "ext-curl-c",
      "version": "0.1.4",
      "url": "/agent/latest/packages/ext-curl-c/0.1.4/index.json",
      "description": "HTTP(S) client bindings via libcurl (run-os only).",
      "docs_url": "/agent/latest/packages/ext-curl-c/0.1.4/index.json#docs"
    },
    {
      "name": "ext-curl-c",
      "version": "0.1.5",
      "url": "/agent/latest/packages/ext-curl-c/0.1.5/index.json",
      "description": "HTTP(S) client bindings via libcurl (run-os only).",
      "docs_url": "/agent/latest/packages/ext-curl-c/0.1.5/index.json#docs"
    },
    {
      "name": "ext-curl-c",
      "version": "0.1.6",
      "url": "/agent/latest/packages/ext-curl-c/0.1.6/index.json",
      "description": "HTTP(S) client bindings via libcurl (run-os only).",
      "docs_url": "/agent/latest/packages/ext-curl-c/0.1.6/index.json#docs"
    },
    {
      "name": "ext-data-model",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-data-model/0.1.0/index.json",
      "description": "",
      "docs_url": "/agent/latest/packages/ext-data-model/0.1.0/index.json#docs"
    },
    {
      "name": "ext-data-model",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-data-model/0.1.1/index.json",
      "description": "Typed data model with JSON/TOML/YAML codecs.",
      "docs_url": "/agent/latest/packages/ext-data-model/0.1.1/index.json#docs"
    },
    {
      "name": "ext-data-model",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-data-model/0.1.2/index.json",
      "description": "Typed data model with JSON/TOML/YAML codecs.",
      "docs_url": "/agent/latest/packages/ext-data-model/0.1.2/index.json#docs"
    },
    {
      "name": "ext-data-model",
      "version": "0.1.3",
      "url": "/agent/latest/packages/ext-data-model/0.1.3/index.json",
      "description": "Typed data model with JSON/TOML/YAML codecs.",
      "docs_url": "/agent/latest/packages/ext-data-model/0.1.3/index.json#docs"
    },
    {
      "name": "ext-data-model",
      "version": "0.1.4",
      "url": "/agent/latest/packages/ext-data-model/0.1.4/index.json",
      "description": "Typed data model with JSON/TOML/YAML codecs.",
      "docs_url": "/agent/latest/packages/ext-data-model/0.1.4/index.json#docs"
    },
    {
      "name": "ext-data-model",
      "version": "0.1.5",
      "url": "/agent/latest/packages/ext-data-model/0.1.5/index.json",
      "description": "Typed data model with JSON/TOML/YAML codecs.",
      "docs_url": "/agent/latest/packages/ext-data-model/0.1.5/index.json#docs"
    },
    {
      "name": "ext-data-model",
      "version": "0.1.6",
      "url": "/agent/latest/packages/ext-data-model/0.1.6/index.json",
      "description": "Typed data model with JSON/TOML/YAML codecs.",
      "docs_url": "/agent/latest/packages/ext-data-model/0.1.6/index.json#docs"
    },
    {
      "name": "ext-data-model",
      "version": "0.1.7",
      "url": "/agent/latest/packages/ext-data-model/0.1.7/index.json",
      "description": "Typed data model with JSON/TOML/YAML codecs.",
      "docs_url": "/agent/latest/packages/ext-data-model/0.1.7/index.json#docs"
    },
    {
      "name": "ext-db-core",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-db-core/0.1.0/index.json",
      "description": "",
      "docs_url": "/agent/latest/packages/ext-db-core/0.1.0/index.json#docs"
    },
    {
      "name": "ext-db-core",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-db-core/0.1.1/index.json",
      "description": "Database interfaces, query specs, and pooling (run-os only).",
      "docs_url": "/agent/latest/packages/ext-db-core/0.1.1/index.json#docs"
    },
    {
      "name": "ext-db-core",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-db-core/0.1.2/index.json",
      "description": "Database interfaces, query specs, and pooling (run-os only).",
      "docs_url": "/agent/latest/packages/ext-db-core/0.1.2/index.json#docs"
    },
    {
      "name": "ext-db-core",
      "version": "0.1.3",
      "url": "/agent/latest/packages/ext-db-core/0.1.3/index.json",
      "description": "Database interfaces, query specs, and pooling (run-os only).",
      "docs_url": "/agent/latest/packages/ext-db-core/0.1.3/index.json#docs"
    },
    {
      "name": "ext-db-core",
      "version": "0.1.4",
      "url": "/agent/latest/packages/ext-db-core/0.1.4/index.json",
      "description": "Database interfaces, query specs, and pooling (run-os only).",
      "docs_url": "/agent/latest/packages/ext-db-core/0.1.4/index.json#docs"
    },
    {
      "name": "ext-db-core",
      "version": "0.1.5",
      "url": "/agent/latest/packages/ext-db-core/0.1.5/index.json",
      "description": "Database interfaces, query specs, and pooling (run-os only).",
      "docs_url": "/agent/latest/packages/ext-db-core/0.1.5/index.json#docs"
    },
    {
      "name": "ext-db-core",
      "version": "0.1.6",
      "url": "/agent/latest/packages/ext-db-core/0.1.6/index.json",
      "description": "Database interfaces, query specs, and pooling (run-os only).",
      "docs_url": "/agent/latest/packages/ext-db-core/0.1.6/index.json#docs"
    },
    {
      "name": "ext-db-core",
      "version": "0.1.7",
      "url": "/agent/latest/packages/ext-db-core/0.1.7/index.json",
      "description": "Database interfaces, query specs, and pooling (run-os only).",
      "docs_url": "/agent/latest/packages/ext-db-core/0.1.7/index.json#docs"
    },
    {
      "name": "ext-db-core",
      "version": "0.1.8",
      "url": "/agent/latest/packages/ext-db-core/0.1.8/index.json",
      "description": "Database interfaces, query specs, and pooling (run-os only).",
      "docs_url": "/agent/latest/packages/ext-db-core/0.1.8/index.json#docs"
    },
    {
      "name": "ext-db-mysql",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-db-mysql/0.1.0/index.json",
      "description": "",
      "docs_url": "/agent/latest/packages/ext-db-mysql/0.1.0/index.json#docs"
    },
    {
      "name": "ext-db-mysql",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-db-mysql/0.1.1/index.json",
      "description": "MySQL driver for std.db (run-os only).",
      "docs_url": "/agent/latest/packages/ext-db-mysql/0.1.1/index.json#docs"
    },
    {
      "name": "ext-db-mysql",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-db-mysql/0.1.2/index.json",
      "description": "MySQL driver for std.db (run-os only).",
      "docs_url": "/agent/latest/packages/ext-db-mysql/0.1.2/index.json#docs"
    },
    {
      "name": "ext-db-mysql",
      "version": "0.1.3",
      "url": "/agent/latest/packages/ext-db-mysql/0.1.3/index.json",
      "description": "MySQL driver for std.db (run-os only).",
      "docs_url": "/agent/latest/packages/ext-db-mysql/0.1.3/index.json#docs"
    },
    {
      "name": "ext-db-mysql",
      "version": "0.1.4",
      "url": "/agent/latest/packages/ext-db-mysql/0.1.4/index.json",
      "description": "MySQL driver for std.db (run-os only).",
      "docs_url": "/agent/latest/packages/ext-db-mysql/0.1.4/index.json#docs"
    },
    {
      "name": "ext-db-mysql",
      "version": "0.1.5",
      "url": "/agent/latest/packages/ext-db-mysql/0.1.5/index.json",
      "description": "MySQL driver for std.db (run-os only).",
      "docs_url": "/agent/latest/packages/ext-db-mysql/0.1.5/index.json#docs"
    },
    {
      "name": "ext-db-postgres",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-db-postgres/0.1.0/index.json",
      "description": "",
      "docs_url": "/agent/latest/packages/ext-db-postgres/0.1.0/index.json#docs"
    },
    {
      "name": "ext-db-postgres",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-db-postgres/0.1.1/index.json",
      "description": "PostgreSQL driver for std.db (run-os only).",
      "docs_url": "/agent/latest/packages/ext-db-postgres/0.1.1/index.json#docs"
    },
    {
      "name": "ext-db-postgres",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-db-postgres/0.1.2/index.json",
      "description": "PostgreSQL driver for std.db (run-os only).",
      "docs_url": "/agent/latest/packages/ext-db-postgres/0.1.2/index.json#docs"
    },
    {
      "name": "ext-db-postgres",
      "version": "0.1.3",
      "url": "/agent/latest/packages/ext-db-postgres/0.1.3/index.json",
      "description": "PostgreSQL driver for std.db (run-os only).",
      "docs_url": "/agent/latest/packages/ext-db-postgres/0.1.3/index.json#docs"
    },
    {
      "name": "ext-db-postgres",
      "version": "0.1.4",
      "url": "/agent/latest/packages/ext-db-postgres/0.1.4/index.json",
      "description": "PostgreSQL driver for std.db (run-os only).",
      "docs_url": "/agent/latest/packages/ext-db-postgres/0.1.4/index.json#docs"
    },
    {
      "name": "ext-db-postgres",
      "version": "0.1.5",
      "url": "/agent/latest/packages/ext-db-postgres/0.1.5/index.json",
      "description": "PostgreSQL driver for std.db (run-os only).",
      "docs_url": "/agent/latest/packages/ext-db-postgres/0.1.5/index.json#docs"
    },
    {
      "name": "ext-db-redis",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-db-redis/0.1.0/index.json",
      "description": "",
      "docs_url": "/agent/latest/packages/ext-db-redis/0.1.0/index.json#docs"
    },
    {
      "name": "ext-db-redis",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-db-redis/0.1.1/index.json",
      "description": "Redis client for std.db (run-os only).",
      "docs_url": "/agent/latest/packages/ext-db-redis/0.1.1/index.json#docs"
    },
    {
      "name": "ext-db-redis",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-db-redis/0.1.2/index.json",
      "description": "Redis client for std.db (run-os only).",
      "docs_url": "/agent/latest/packages/ext-db-redis/0.1.2/index.json#docs"
    },
    {
      "name": "ext-db-redis",
      "version": "0.1.3",
      "url": "/agent/latest/packages/ext-db-redis/0.1.3/index.json",
      "description": "Redis client for std.db (run-os only).",
      "docs_url": "/agent/latest/packages/ext-db-redis/0.1.3/index.json#docs"
    },
    {
      "name": "ext-db-redis",
      "version": "0.1.4",
      "url": "/agent/latest/packages/ext-db-redis/0.1.4/index.json",
      "description": "Redis client for std.db (run-os only).",
      "docs_url": "/agent/latest/packages/ext-db-redis/0.1.4/index.json#docs"
    },
    {
      "name": "ext-db-sqlite",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-db-sqlite/0.1.0/index.json",
      "description": "",
      "docs_url": "/agent/latest/packages/ext-db-sqlite/0.1.0/index.json#docs"
    },
    {
      "name": "ext-db-sqlite",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-db-sqlite/0.1.1/index.json",
      "description": "SQLite driver for std.db (run-os only).",
      "docs_url": "/agent/latest/packages/ext-db-sqlite/0.1.1/index.json#docs"
    },
    {
      "name": "ext-db-sqlite",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-db-sqlite/0.1.2/index.json",
      "description": "SQLite driver for std.db (run-os only).",
      "docs_url": "/agent/latest/packages/ext-db-sqlite/0.1.2/index.json#docs"
    },
    {
      "name": "ext-db-sqlite",
      "version": "0.1.3",
      "url": "/agent/latest/packages/ext-db-sqlite/0.1.3/index.json",
      "description": "SQLite driver for std.db (run-os only).",
      "docs_url": "/agent/latest/packages/ext-db-sqlite/0.1.3/index.json#docs"
    },
    {
      "name": "ext-db-sqlite",
      "version": "0.1.4",
      "url": "/agent/latest/packages/ext-db-sqlite/0.1.4/index.json",
      "description": "SQLite driver for std.db (run-os only).",
      "docs_url": "/agent/latest/packages/ext-db-sqlite/0.1.4/index.json#docs"
    },
    {
      "name": "ext-db-sqlite",
      "version": "0.1.5",
      "url": "/agent/latest/packages/ext-db-sqlite/0.1.5/index.json",
      "description": "SQLite driver for std.db (run-os only).",
      "docs_url": "/agent/latest/packages/ext-db-sqlite/0.1.5/index.json#docs"
    },
    {
      "name": "ext-db-sqlite",
      "version": "0.1.6",
      "url": "/agent/latest/packages/ext-db-sqlite/0.1.6/index.json",
      "description": "SQLite driver for std.db (run-os only).",
      "docs_url": "/agent/latest/packages/ext-db-sqlite/0.1.6/index.json#docs"
    },
    {
      "name": "ext-db-sqlite",
      "version": "0.1.7",
      "url": "/agent/latest/packages/ext-db-sqlite/0.1.7/index.json",
      "description": "SQLite driver for std.db (run-os only).",
      "docs_url": "/agent/latest/packages/ext-db-sqlite/0.1.7/index.json#docs"
    },
    {
      "name": "ext-decimal-rs",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-decimal-rs/0.1.0/index.json",
      "description": "Fixed-point decimal utilities (codec_v1, parse, format, basic ops).",
      "docs_url": "/agent/latest/packages/ext-decimal-rs/0.1.0/index.json#docs"
    },
    {
      "name": "ext-decimal-rs",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-decimal-rs/0.1.1/index.json",
      "description": "Fixed-point decimal utilities (codec_v1, parse, format, basic ops).",
      "docs_url": "/agent/latest/packages/ext-decimal-rs/0.1.1/index.json#docs"
    },
    {
      "name": "ext-decimal-rs",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-decimal-rs/0.1.2/index.json",
      "description": "Fixed-point decimal utilities (codec_v1, parse, format, basic ops).",
      "docs_url": "/agent/latest/packages/ext-decimal-rs/0.1.2/index.json#docs"
    },
    {
      "name": "ext-diff-rs",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-diff-rs/0.1.0/index.json",
      "description": "Deterministic diff + patch helpers (bytes/lines) with a stable patch_v1 format.",
      "docs_url": "/agent/latest/packages/ext-diff-rs/0.1.0/index.json#docs"
    },
    {
      "name": "ext-diff-rs",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-diff-rs/0.1.1/index.json",
      "description": "Deterministic diff + patch helpers (bytes/lines) with a stable patch_v1 format.",
      "docs_url": "/agent/latest/packages/ext-diff-rs/0.1.1/index.json#docs"
    },
    {
      "name": "ext-diff-rs",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-diff-rs/0.1.2/index.json",
      "description": "Deterministic diff + patch helpers (bytes/lines) with a stable patch_v1 format.",
      "docs_url": "/agent/latest/packages/ext-diff-rs/0.1.2/index.json#docs"
    },
    {
      "name": "ext-error",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-error/0.1.0/index.json",
      "description": "",
      "docs_url": "/agent/latest/packages/ext-error/0.1.0/index.json#docs"
    },
    {
      "name": "ext-error",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-error/0.1.1/index.json",
      "description": "Error chaining, context, and formatting helpers.",
      "docs_url": "/agent/latest/packages/ext-error/0.1.1/index.json#docs"
    },
    {
      "name": "ext-error",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-error/0.1.2/index.json",
      "description": "Error chaining, context, and formatting helpers.",
      "docs_url": "/agent/latest/packages/ext-error/0.1.2/index.json#docs"
    },
    {
      "name": "ext-error",
      "version": "0.1.3",
      "url": "/agent/latest/packages/ext-error/0.1.3/index.json",
      "description": "Error chaining, context, and formatting helpers.",
      "docs_url": "/agent/latest/packages/ext-error/0.1.3/index.json#docs"
    },
    {
      "name": "ext-error",
      "version": "0.1.4",
      "url": "/agent/latest/packages/ext-error/0.1.4/index.json",
      "description": "Error chaining, context, and formatting helpers.",
      "docs_url": "/agent/latest/packages/ext-error/0.1.4/index.json#docs"
    },
    {
      "name": "ext-fs",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-fs/0.1.0/index.json",
      "description": "",
      "docs_url": "/agent/latest/packages/ext-fs/0.1.0/index.json#docs"
    },
    {
      "name": "ext-fs",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-fs/0.1.1/index.json",
      "description": "OS filesystem API (run-os only).",
      "docs_url": "/agent/latest/packages/ext-fs/0.1.1/index.json#docs"
    },
    {
      "name": "ext-fs",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-fs/0.1.2/index.json",
      "description": "OS filesystem API (run-os only).",
      "docs_url": "/agent/latest/packages/ext-fs/0.1.2/index.json#docs"
    },
    {
      "name": "ext-fs",
      "version": "0.1.3",
      "url": "/agent/latest/packages/ext-fs/0.1.3/index.json",
      "description": "OS filesystem API (run-os only).",
      "docs_url": "/agent/latest/packages/ext-fs/0.1.3/index.json#docs"
    },
    {
      "name": "ext-fs",
      "version": "0.1.4",
      "url": "/agent/latest/packages/ext-fs/0.1.4/index.json",
      "description": "OS filesystem API (run-os only).",
      "docs_url": "/agent/latest/packages/ext-fs/0.1.4/index.json#docs"
    },
    {
      "name": "ext-glob-rs",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-glob-rs/0.1.0/index.json",
      "description": "Wildcard (glob-like) matching for ASCII paths and tokens.",
      "docs_url": "/agent/latest/packages/ext-glob-rs/0.1.0/index.json#docs"
    },
    {
      "name": "ext-glob-rs",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-glob-rs/0.1.1/index.json",
      "description": "Wildcard (glob-like) matching for ASCII paths and tokens.",
      "docs_url": "/agent/latest/packages/ext-glob-rs/0.1.1/index.json#docs"
    },
    {
      "name": "ext-glob-rs",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-glob-rs/0.1.2/index.json",
      "description": "Wildcard (glob-like) matching for ASCII paths and tokens.",
      "docs_url": "/agent/latest/packages/ext-glob-rs/0.1.2/index.json#docs"
    },
    {
      "name": "ext-glob-rs",
      "version": "0.1.3",
      "url": "/agent/latest/packages/ext-glob-rs/0.1.3/index.json",
      "description": "Wildcard (glob-like) matching for ASCII paths and tokens.",
      "docs_url": "/agent/latest/packages/ext-glob-rs/0.1.3/index.json#docs"
    },
    {
      "name": "ext-hex-rs",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-hex-rs/0.1.0/index.json",
      "description": "",
      "docs_url": "/agent/latest/packages/ext-hex-rs/0.1.0/index.json#docs"
    },
    {
      "name": "ext-hex-rs",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-hex-rs/0.1.1/index.json",
      "description": "Hex encoding and decoding.",
      "docs_url": "/agent/latest/packages/ext-hex-rs/0.1.1/index.json#docs"
    },
    {
      "name": "ext-hex-rs",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-hex-rs/0.1.2/index.json",
      "description": "Hex encoding and decoding.",
      "docs_url": "/agent/latest/packages/ext-hex-rs/0.1.2/index.json#docs"
    },
    {
      "name": "ext-hex-rs",
      "version": "0.1.3",
      "url": "/agent/latest/packages/ext-hex-rs/0.1.3/index.json",
      "description": "Hex encoding and decoding.",
      "docs_url": "/agent/latest/packages/ext-hex-rs/0.1.3/index.json#docs"
    },
    {
      "name": "ext-hex-rs",
      "version": "0.1.4",
      "url": "/agent/latest/packages/ext-hex-rs/0.1.4/index.json",
      "description": "Hex encoding and decoding.",
      "docs_url": "/agent/latest/packages/ext-hex-rs/0.1.4/index.json#docs"
    },
    {
      "name": "ext-html-lite-rs",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-html-lite-rs/0.1.0/index.json",
      "description": "HTML link and visible-text extraction helpers (lightweight, deterministic).",
      "docs_url": "/agent/latest/packages/ext-html-lite-rs/0.1.0/index.json#docs"
    },
    {
      "name": "ext-html-lite-rs",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-html-lite-rs/0.1.1/index.json",
      "description": "HTML link and visible-text extraction helpers (lightweight, deterministic).",
      "docs_url": "/agent/latest/packages/ext-html-lite-rs/0.1.1/index.json#docs"
    },
    {
      "name": "ext-html-lite-rs",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-html-lite-rs/0.1.2/index.json",
      "description": "HTML link and visible-text extraction helpers (lightweight, deterministic).",
      "docs_url": "/agent/latest/packages/ext-html-lite-rs/0.1.2/index.json#docs"
    },
    {
      "name": "ext-ini-rs",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-ini-rs/0.1.0/index.json",
      "description": "",
      "docs_url": "/agent/latest/packages/ext-ini-rs/0.1.0/index.json#docs"
    },
    {
      "name": "ext-ini-rs",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-ini-rs/0.1.1/index.json",
      "description": "INI parsing and writing.",
      "docs_url": "/agent/latest/packages/ext-ini-rs/0.1.1/index.json#docs"
    },
    {
      "name": "ext-ini-rs",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-ini-rs/0.1.2/index.json",
      "description": "INI parsing and writing.",
      "docs_url": "/agent/latest/packages/ext-ini-rs/0.1.2/index.json#docs"
    },
    {
      "name": "ext-ini-rs",
      "version": "0.1.3",
      "url": "/agent/latest/packages/ext-ini-rs/0.1.3/index.json",
      "description": "INI parsing and writing.",
      "docs_url": "/agent/latest/packages/ext-ini-rs/0.1.3/index.json#docs"
    },
    {
      "name": "ext-ini-rs",
      "version": "0.1.4",
      "url": "/agent/latest/packages/ext-ini-rs/0.1.4/index.json",
      "description": "INI parsing and writing.",
      "docs_url": "/agent/latest/packages/ext-ini-rs/0.1.4/index.json#docs"
    },
    {
      "name": "ext-json-rs",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-json-rs/0.1.0/index.json",
      "description": "",
      "docs_url": "/agent/latest/packages/ext-json-rs/0.1.0/index.json#docs"
    },
    {
      "name": "ext-json-rs",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-json-rs/0.1.1/index.json",
      "description": "JSON canonicalization, JSON Pointer, and ext.data_model parsing.",
      "docs_url": "/agent/latest/packages/ext-json-rs/0.1.1/index.json#docs"
    },
    {
      "name": "ext-json-rs",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-json-rs/0.1.2/index.json",
      "description": "JSON canonicalization, JSON Pointer, and ext.data_model parsing.",
      "docs_url": "/agent/latest/packages/ext-json-rs/0.1.2/index.json#docs"
    },
    {
      "name": "ext-json-rs",
      "version": "0.1.3",
      "url": "/agent/latest/packages/ext-json-rs/0.1.3/index.json",
      "description": "JSON canonicalization, JSON Pointer, and ext.data_model parsing.",
      "docs_url": "/agent/latest/packages/ext-json-rs/0.1.3/index.json#docs"
    },
    {
      "name": "ext-json-rs",
      "version": "0.1.4",
      "url": "/agent/latest/packages/ext-json-rs/0.1.4/index.json",
      "description": "JSON canonicalization, JSON Pointer, and ext.data_model parsing.",
      "docs_url": "/agent/latest/packages/ext-json-rs/0.1.4/index.json#docs"
    },
    {
      "name": "ext-log",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-log/0.1.0/index.json",
      "description": "",
      "docs_url": "/agent/latest/packages/ext-log/0.1.0/index.json#docs"
    },
    {
      "name": "ext-log",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-log/0.1.1/index.json",
      "description": "Log record encoding and formatting helpers.",
      "docs_url": "/agent/latest/packages/ext-log/0.1.1/index.json#docs"
    },
    {
      "name": "ext-log",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-log/0.1.2/index.json",
      "description": "Log record encoding and formatting helpers.",
      "docs_url": "/agent/latest/packages/ext-log/0.1.2/index.json#docs"
    },
    {
      "name": "ext-log",
      "version": "0.1.3",
      "url": "/agent/latest/packages/ext-log/0.1.3/index.json",
      "description": "Log record encoding and formatting helpers.",
      "docs_url": "/agent/latest/packages/ext-log/0.1.3/index.json#docs"
    },
    {
      "name": "ext-log",
      "version": "0.1.4",
      "url": "/agent/latest/packages/ext-log/0.1.4/index.json",
      "description": "Log record encoding and formatting helpers.",
      "docs_url": "/agent/latest/packages/ext-log/0.1.4/index.json#docs"
    },
    {
      "name": "ext-math",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-math/0.1.0/index.json",
      "description": "",
      "docs_url": "/agent/latest/packages/ext-math/0.1.0/index.json#docs"
    },
    {
      "name": "ext-math",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-math/0.1.1/index.json",
      "description": "Math utilities (integers and f64).",
      "docs_url": "/agent/latest/packages/ext-math/0.1.1/index.json#docs"
    },
    {
      "name": "ext-math",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-math/0.1.2/index.json",
      "description": "Math utilities (integers and f64).",
      "docs_url": "/agent/latest/packages/ext-math/0.1.2/index.json#docs"
    },
    {
      "name": "ext-math",
      "version": "0.1.3",
      "url": "/agent/latest/packages/ext-math/0.1.3/index.json",
      "description": "Math utilities (integers and f64).",
      "docs_url": "/agent/latest/packages/ext-math/0.1.3/index.json#docs"
    },
    {
      "name": "ext-math",
      "version": "0.1.4",
      "url": "/agent/latest/packages/ext-math/0.1.4/index.json",
      "description": "Math utilities (integers and f64).",
      "docs_url": "/agent/latest/packages/ext-math/0.1.4/index.json#docs"
    },
    {
      "name": "ext-memchr-rs",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-memchr-rs/0.1.0/index.json",
      "description": "",
      "docs_url": "/agent/latest/packages/ext-memchr-rs/0.1.0/index.json#docs"
    },
    {
      "name": "ext-memchr-rs",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-memchr-rs/0.1.1/index.json",
      "description": "Byte search primitives (memchr/memrchr).",
      "docs_url": "/agent/latest/packages/ext-memchr-rs/0.1.1/index.json#docs"
    },
    {
      "name": "ext-memchr-rs",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-memchr-rs/0.1.2/index.json",
      "description": "Byte search primitives (memchr/memrchr).",
      "docs_url": "/agent/latest/packages/ext-memchr-rs/0.1.2/index.json#docs"
    },
    {
      "name": "ext-memchr-rs",
      "version": "0.1.3",
      "url": "/agent/latest/packages/ext-memchr-rs/0.1.3/index.json",
      "description": "Byte search primitives (memchr/memrchr).",
      "docs_url": "/agent/latest/packages/ext-memchr-rs/0.1.3/index.json#docs"
    },
    {
      "name": "ext-memchr-rs",
      "version": "0.1.4",
      "url": "/agent/latest/packages/ext-memchr-rs/0.1.4/index.json",
      "description": "Byte search primitives (memchr/memrchr).",
      "docs_url": "/agent/latest/packages/ext-memchr-rs/0.1.4/index.json#docs"
    },
    {
      "name": "ext-msgpack-rs",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-msgpack-rs/0.1.0/index.json",
      "description": "MessagePack encode/decode with ext.data_model integration.",
      "docs_url": "/agent/latest/packages/ext-msgpack-rs/0.1.0/index.json#docs"
    },
    {
      "name": "ext-msgpack-rs",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-msgpack-rs/0.1.1/index.json",
      "description": "MessagePack encode/decode with ext.data_model integration.",
      "docs_url": "/agent/latest/packages/ext-msgpack-rs/0.1.1/index.json#docs"
    },
    {
      "name": "ext-msgpack-rs",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-msgpack-rs/0.1.2/index.json",
      "description": "MessagePack encode/decode with ext.data_model integration.",
      "docs_url": "/agent/latest/packages/ext-msgpack-rs/0.1.2/index.json#docs"
    },
    {
      "name": "ext-msgpack-rs",
      "version": "0.1.3",
      "url": "/agent/latest/packages/ext-msgpack-rs/0.1.3/index.json",
      "description": "MessagePack encode/decode with ext.data_model integration.",
      "docs_url": "/agent/latest/packages/ext-msgpack-rs/0.1.3/index.json#docs"
    },
    {
      "name": "ext-msgpack-rs",
      "version": "0.1.4",
      "url": "/agent/latest/packages/ext-msgpack-rs/0.1.4/index.json",
      "description": "MessagePack encode/decode with ext.data_model integration.",
      "docs_url": "/agent/latest/packages/ext-msgpack-rs/0.1.4/index.json#docs"
    },
    {
      "name": "ext-msgpack-rs",
      "version": "0.1.5",
      "url": "/agent/latest/packages/ext-msgpack-rs/0.1.5/index.json",
      "description": "MessagePack encode/decode with ext.data_model integration.",
      "docs_url": "/agent/latest/packages/ext-msgpack-rs/0.1.5/index.json#docs"
    },
    {
      "name": "ext-net",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-net/0.1.0/index.json",
      "description": "",
      "docs_url": "/agent/latest/packages/ext-net/0.1.0/index.json#docs"
    },
    {
      "name": "ext-net",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-net/0.1.1/index.json",
      "description": "Networking APIs (DNS, TCP/UDP, TLS, HTTP) (run-os only).",
      "docs_url": "/agent/latest/packages/ext-net/0.1.1/index.json#docs"
    },
    {
      "name": "ext-net",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-net/0.1.2/index.json",
      "description": "Networking APIs (DNS, TCP/UDP, TLS, HTTP) (run-os only).",
      "docs_url": "/agent/latest/packages/ext-net/0.1.2/index.json#docs"
    },
    {
      "name": "ext-net",
      "version": "0.1.3",
      "url": "/agent/latest/packages/ext-net/0.1.3/index.json",
      "description": "Networking APIs (DNS, TCP/UDP, TLS, HTTP) (run-os only).",
      "docs_url": "/agent/latest/packages/ext-net/0.1.3/index.json#docs"
    },
    {
      "name": "ext-net",
      "version": "0.1.4",
      "url": "/agent/latest/packages/ext-net/0.1.4/index.json",
      "description": "Networking APIs (DNS, TCP/UDP, TLS, HTTP) (run-os only).",
      "docs_url": "/agent/latest/packages/ext-net/0.1.4/index.json#docs"
    },
    {
      "name": "ext-net",
      "version": "0.1.5",
      "url": "/agent/latest/packages/ext-net/0.1.5/index.json",
      "description": "Networking APIs (DNS, TCP/UDP, TLS, HTTP) (run-os only).",
      "docs_url": "/agent/latest/packages/ext-net/0.1.5/index.json#docs"
    },
    {
      "name": "ext-net",
      "version": "0.1.6",
      "url": "/agent/latest/packages/ext-net/0.1.6/index.json",
      "description": "Networking APIs (DNS, TCP/UDP, TLS, HTTP) (run-os only).",
      "docs_url": "/agent/latest/packages/ext-net/0.1.6/index.json#docs"
    },
    {
      "name": "ext-net",
      "version": "0.1.7",
      "url": "/agent/latest/packages/ext-net/0.1.7/index.json",
      "description": "Networking APIs (DNS, TCP/UDP, TLS, HTTP) (run-os only).",
      "docs_url": "/agent/latest/packages/ext-net/0.1.7/index.json#docs"
    },
    {
      "name": "ext-openssl-c",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-openssl-c/0.1.0/index.json",
      "description": "",
      "docs_url": "/agent/latest/packages/ext-openssl-c/0.1.0/index.json#docs"
    },
    {
      "name": "ext-openssl-c",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-openssl-c/0.1.1/index.json",
      "description": "OpenSSL bindings: hashes, RNG, and Ed25519 (run-os only).",
      "docs_url": "/agent/latest/packages/ext-openssl-c/0.1.1/index.json#docs"
    },
    {
      "name": "ext-openssl-c",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-openssl-c/0.1.2/index.json",
      "description": "OpenSSL bindings: hashes, RNG, and Ed25519 (run-os only).",
      "docs_url": "/agent/latest/packages/ext-openssl-c/0.1.2/index.json#docs"
    },
    {
      "name": "ext-openssl-c",
      "version": "0.1.3",
      "url": "/agent/latest/packages/ext-openssl-c/0.1.3/index.json",
      "description": "OpenSSL bindings: hashes, RNG, and Ed25519 (run-os only).",
      "docs_url": "/agent/latest/packages/ext-openssl-c/0.1.3/index.json#docs"
    },
    {
      "name": "ext-openssl-c",
      "version": "0.1.4",
      "url": "/agent/latest/packages/ext-openssl-c/0.1.4/index.json",
      "description": "OpenSSL bindings: hashes, RNG, and Ed25519 (run-os only).",
      "docs_url": "/agent/latest/packages/ext-openssl-c/0.1.4/index.json#docs"
    },
    {
      "name": "ext-openssl-c",
      "version": "0.1.5",
      "url": "/agent/latest/packages/ext-openssl-c/0.1.5/index.json",
      "description": "OpenSSL bindings: hashes, RNG, and Ed25519 (run-os only).",
      "docs_url": "/agent/latest/packages/ext-openssl-c/0.1.5/index.json#docs"
    },
    {
      "name": "ext-path-glob-rs",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-path-glob-rs/0.1.0/index.json",
      "description": "OS-world glob + walk helpers under std.os.fs.* (deterministic ordering).",
      "docs_url": "/agent/latest/packages/ext-path-glob-rs/0.1.0/index.json#docs"
    },
    {
      "name": "ext-path-glob-rs",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-path-glob-rs/0.1.1/index.json",
      "description": "OS-world glob + walk helpers under std.os.fs.* (deterministic ordering).",
      "docs_url": "/agent/latest/packages/ext-path-glob-rs/0.1.1/index.json#docs"
    },
    {
      "name": "ext-path-glob-rs",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-path-glob-rs/0.1.2/index.json",
      "description": "OS-world glob + walk helpers under std.os.fs.* (deterministic ordering).",
      "docs_url": "/agent/latest/packages/ext-path-glob-rs/0.1.2/index.json#docs"
    },
    {
      "name": "ext-pb-rs",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-pb-rs/0.1.0/index.json",
      "description": "",
      "docs_url": "/agent/latest/packages/ext-pb-rs/0.1.0/index.json#docs"
    },
    {
      "name": "ext-pb-rs",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-pb-rs/0.1.1/index.json",
      "description": "Protocol Buffers wire format and ext.data_model integration.",
      "docs_url": "/agent/latest/packages/ext-pb-rs/0.1.1/index.json#docs"
    },
    {
      "name": "ext-pb-rs",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-pb-rs/0.1.2/index.json",
      "description": "Protocol Buffers wire format and ext.data_model integration.",
      "docs_url": "/agent/latest/packages/ext-pb-rs/0.1.2/index.json#docs"
    },
    {
      "name": "ext-pb-rs",
      "version": "0.1.3",
      "url": "/agent/latest/packages/ext-pb-rs/0.1.3/index.json",
      "description": "Protocol Buffers wire format and ext.data_model integration.",
      "docs_url": "/agent/latest/packages/ext-pb-rs/0.1.3/index.json#docs"
    },
    {
      "name": "ext-pb-rs",
      "version": "0.1.4",
      "url": "/agent/latest/packages/ext-pb-rs/0.1.4/index.json",
      "description": "Protocol Buffers wire format and ext.data_model integration.",
      "docs_url": "/agent/latest/packages/ext-pb-rs/0.1.4/index.json#docs"
    },
    {
      "name": "ext-pb-rs",
      "version": "0.1.5",
      "url": "/agent/latest/packages/ext-pb-rs/0.1.5/index.json",
      "description": "Protocol Buffers wire format and ext.data_model integration.",
      "docs_url": "/agent/latest/packages/ext-pb-rs/0.1.5/index.json#docs"
    },
    {
      "name": "ext-regex",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-regex/0.1.0/index.json",
      "description": "",
      "docs_url": "/agent/latest/packages/ext-regex/0.1.0/index.json#docs"
    },
    {
      "name": "ext-regex",
      "version": "0.2.0",
      "url": "/agent/latest/packages/ext-regex/0.2.0/index.json",
      "description": "",
      "docs_url": "/agent/latest/packages/ext-regex/0.2.0/index.json#docs"
    },
    {
      "name": "ext-regex",
      "version": "0.2.1",
      "url": "/agent/latest/packages/ext-regex/0.2.1/index.json",
      "description": "Regular expression matching and searching.",
      "docs_url": "/agent/latest/packages/ext-regex/0.2.1/index.json#docs"
    },
    {
      "name": "ext-regex",
      "version": "0.2.2",
      "url": "/agent/latest/packages/ext-regex/0.2.2/index.json",
      "description": "Regular expression matching and searching.",
      "docs_url": "/agent/latest/packages/ext-regex/0.2.2/index.json#docs"
    },
    {
      "name": "ext-regex",
      "version": "0.2.3",
      "url": "/agent/latest/packages/ext-regex/0.2.3/index.json",
      "description": "Regular expression matching and searching.",
      "docs_url": "/agent/latest/packages/ext-regex/0.2.3/index.json#docs"
    },
    {
      "name": "ext-regex",
      "version": "0.2.4",
      "url": "/agent/latest/packages/ext-regex/0.2.4/index.json",
      "description": "Regular expression matching and searching.",
      "docs_url": "/agent/latest/packages/ext-regex/0.2.4/index.json#docs"
    },
    {
      "name": "ext-robots-txt-rs",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-robots-txt-rs/0.1.0/index.json",
      "description": "robots.txt parsing helpers (allow/disallow evaluation).",
      "docs_url": "/agent/latest/packages/ext-robots-txt-rs/0.1.0/index.json#docs"
    },
    {
      "name": "ext-robots-txt-rs",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-robots-txt-rs/0.1.1/index.json",
      "description": "robots.txt parsing helpers (allow/disallow evaluation).",
      "docs_url": "/agent/latest/packages/ext-robots-txt-rs/0.1.1/index.json#docs"
    },
    {
      "name": "ext-robots-txt-rs",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-robots-txt-rs/0.1.2/index.json",
      "description": "robots.txt parsing helpers (allow/disallow evaluation).",
      "docs_url": "/agent/latest/packages/ext-robots-txt-rs/0.1.2/index.json#docs"
    },
    {
      "name": "ext-robots-txt-rs",
      "version": "0.1.3",
      "url": "/agent/latest/packages/ext-robots-txt-rs/0.1.3/index.json",
      "description": "robots.txt parsing helpers (allow/disallow evaluation).",
      "docs_url": "/agent/latest/packages/ext-robots-txt-rs/0.1.3/index.json#docs"
    },
    {
      "name": "ext-semver-rs",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-semver-rs/0.1.0/index.json",
      "description": "",
      "docs_url": "/agent/latest/packages/ext-semver-rs/0.1.0/index.json#docs"
    },
    {
      "name": "ext-semver-rs",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-semver-rs/0.1.1/index.json",
      "description": "Semantic version parsing and comparison.",
      "docs_url": "/agent/latest/packages/ext-semver-rs/0.1.1/index.json#docs"
    },
    {
      "name": "ext-semver-rs",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-semver-rs/0.1.2/index.json",
      "description": "Semantic version parsing and comparison.",
      "docs_url": "/agent/latest/packages/ext-semver-rs/0.1.2/index.json#docs"
    },
    {
      "name": "ext-semver-rs",
      "version": "0.1.3",
      "url": "/agent/latest/packages/ext-semver-rs/0.1.3/index.json",
      "description": "Semantic version parsing and comparison.",
      "docs_url": "/agent/latest/packages/ext-semver-rs/0.1.3/index.json#docs"
    },
    {
      "name": "ext-semver-rs",
      "version": "0.1.4",
      "url": "/agent/latest/packages/ext-semver-rs/0.1.4/index.json",
      "description": "Semantic version parsing and comparison.",
      "docs_url": "/agent/latest/packages/ext-semver-rs/0.1.4/index.json#docs"
    },
    {
      "name": "ext-sitemap-rs",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-sitemap-rs/0.1.0/index.json",
      "description": "Sitemap XML helpers (extract <loc> URLs).",
      "docs_url": "/agent/latest/packages/ext-sitemap-rs/0.1.0/index.json#docs"
    },
    {
      "name": "ext-sitemap-rs",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-sitemap-rs/0.1.1/index.json",
      "description": "Sitemap XML helpers (extract <loc> URLs).",
      "docs_url": "/agent/latest/packages/ext-sitemap-rs/0.1.1/index.json#docs"
    },
    {
      "name": "ext-sitemap-rs",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-sitemap-rs/0.1.2/index.json",
      "description": "Sitemap XML helpers (extract <loc> URLs).",
      "docs_url": "/agent/latest/packages/ext-sitemap-rs/0.1.2/index.json#docs"
    },
    {
      "name": "ext-sitemap-rs",
      "version": "0.1.3",
      "url": "/agent/latest/packages/ext-sitemap-rs/0.1.3/index.json",
      "description": "Sitemap XML helpers (extract <loc> URLs).",
      "docs_url": "/agent/latest/packages/ext-sitemap-rs/0.1.3/index.json#docs"
    },
    {
      "name": "ext-sockets-c",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-sockets-c/0.1.0/index.json",
      "description": "",
      "docs_url": "/agent/latest/packages/ext-sockets-c/0.1.0/index.json#docs"
    },
    {
      "name": "ext-sockets-c",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-sockets-c/0.1.1/index.json",
      "description": "Sockets + TLS FFI backend for std.net (run-os only).",
      "docs_url": "/agent/latest/packages/ext-sockets-c/0.1.1/index.json#docs"
    },
    {
      "name": "ext-sockets-c",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-sockets-c/0.1.2/index.json",
      "description": "Sockets + TLS FFI backend for std.net (run-os only).",
      "docs_url": "/agent/latest/packages/ext-sockets-c/0.1.2/index.json#docs"
    },
    {
      "name": "ext-sockets-c",
      "version": "0.1.3",
      "url": "/agent/latest/packages/ext-sockets-c/0.1.3/index.json",
      "description": "Sockets + TLS FFI backend for std.net (run-os only).",
      "docs_url": "/agent/latest/packages/ext-sockets-c/0.1.3/index.json#docs"
    },
    {
      "name": "ext-sockets-c",
      "version": "0.1.4",
      "url": "/agent/latest/packages/ext-sockets-c/0.1.4/index.json",
      "description": "Sockets + TLS FFI backend for std.net (run-os only).",
      "docs_url": "/agent/latest/packages/ext-sockets-c/0.1.4/index.json#docs"
    },
    {
      "name": "ext-sockets-c",
      "version": "0.1.5",
      "url": "/agent/latest/packages/ext-sockets-c/0.1.5/index.json",
      "description": "Sockets + TLS FFI backend for std.net (run-os only).",
      "docs_url": "/agent/latest/packages/ext-sockets-c/0.1.5/index.json#docs"
    },
    {
      "name": "ext-sockets-c",
      "version": "0.1.6",
      "url": "/agent/latest/packages/ext-sockets-c/0.1.6/index.json",
      "description": "Sockets + TLS FFI backend for std.net (run-os only).",
      "docs_url": "/agent/latest/packages/ext-sockets-c/0.1.6/index.json#docs"
    },
    {
      "name": "ext-streams",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-streams/0.1.0/index.json",
      "description": "",
      "docs_url": "/agent/latest/packages/ext-streams/0.1.0/index.json#docs"
    },
    {
      "name": "ext-streams",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-streams/0.1.1/index.json",
      "description": "Create io readers from bytes and collections.",
      "docs_url": "/agent/latest/packages/ext-streams/0.1.1/index.json#docs"
    },
    {
      "name": "ext-streams",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-streams/0.1.2/index.json",
      "description": "Create io readers from bytes and collections.",
      "docs_url": "/agent/latest/packages/ext-streams/0.1.2/index.json#docs"
    },
    {
      "name": "ext-streams",
      "version": "0.1.3",
      "url": "/agent/latest/packages/ext-streams/0.1.3/index.json",
      "description": "Create io readers from bytes and collections.",
      "docs_url": "/agent/latest/packages/ext-streams/0.1.3/index.json#docs"
    },
    {
      "name": "ext-streams",
      "version": "0.1.4",
      "url": "/agent/latest/packages/ext-streams/0.1.4/index.json",
      "description": "Create io readers from bytes and collections.",
      "docs_url": "/agent/latest/packages/ext-streams/0.1.4/index.json#docs"
    },
    {
      "name": "ext-tar-rs",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-tar-rs/0.1.0/index.json",
      "description": "",
      "docs_url": "/agent/latest/packages/ext-tar-rs/0.1.0/index.json#docs"
    },
    {
      "name": "ext-tar-rs",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-tar-rs/0.1.1/index.json",
      "description": "TAR archive reading and writing.",
      "docs_url": "/agent/latest/packages/ext-tar-rs/0.1.1/index.json#docs"
    },
    {
      "name": "ext-tar-rs",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-tar-rs/0.1.2/index.json",
      "description": "TAR archive reading and writing.",
      "docs_url": "/agent/latest/packages/ext-tar-rs/0.1.2/index.json#docs"
    },
    {
      "name": "ext-tar-rs",
      "version": "0.1.3",
      "url": "/agent/latest/packages/ext-tar-rs/0.1.3/index.json",
      "description": "TAR archive reading and writing.",
      "docs_url": "/agent/latest/packages/ext-tar-rs/0.1.3/index.json#docs"
    },
    {
      "name": "ext-tar-rs",
      "version": "0.1.4",
      "url": "/agent/latest/packages/ext-tar-rs/0.1.4/index.json",
      "description": "TAR archive reading and writing.",
      "docs_url": "/agent/latest/packages/ext-tar-rs/0.1.4/index.json#docs"
    },
    {
      "name": "ext-text",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-text/0.1.0/index.json",
      "description": "Text utilities (trim/split/join/find/lines) built on bytes.",
      "docs_url": "/agent/latest/packages/ext-text/0.1.0/index.json#docs"
    },
    {
      "name": "ext-text",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-text/0.1.1/index.json",
      "description": "Text utilities (trim/split/join/find/lines) built on bytes.",
      "docs_url": "/agent/latest/packages/ext-text/0.1.1/index.json#docs"
    },
    {
      "name": "ext-text",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-text/0.1.2/index.json",
      "description": "Text utilities (trim/split/join/find/lines) built on bytes.",
      "docs_url": "/agent/latest/packages/ext-text/0.1.2/index.json#docs"
    },
    {
      "name": "ext-time-rs",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-time-rs/0.1.0/index.json",
      "description": "",
      "docs_url": "/agent/latest/packages/ext-time-rs/0.1.0/index.json#docs"
    },
    {
      "name": "ext-time-rs",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-time-rs/0.1.1/index.json",
      "description": "Time utilities: durations, RFC 3339, and time zones.",
      "docs_url": "/agent/latest/packages/ext-time-rs/0.1.1/index.json#docs"
    },
    {
      "name": "ext-time-rs",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-time-rs/0.1.2/index.json",
      "description": "Time utilities: durations, RFC 3339, and time zones.",
      "docs_url": "/agent/latest/packages/ext-time-rs/0.1.2/index.json#docs"
    },
    {
      "name": "ext-time-rs",
      "version": "0.1.3",
      "url": "/agent/latest/packages/ext-time-rs/0.1.3/index.json",
      "description": "Time utilities: durations, RFC 3339, and time zones.",
      "docs_url": "/agent/latest/packages/ext-time-rs/0.1.3/index.json#docs"
    },
    {
      "name": "ext-time-rs",
      "version": "0.1.4",
      "url": "/agent/latest/packages/ext-time-rs/0.1.4/index.json",
      "description": "Time utilities: durations, RFC 3339, and time zones.",
      "docs_url": "/agent/latest/packages/ext-time-rs/0.1.4/index.json#docs"
    },
    {
      "name": "ext-time-rs",
      "version": "0.1.5",
      "url": "/agent/latest/packages/ext-time-rs/0.1.5/index.json",
      "description": "Time utilities: durations, RFC 3339, and time zones (run-os only).",
      "docs_url": "/agent/latest/packages/ext-time-rs/0.1.5/index.json#docs"
    },
    {
      "name": "ext-toml-rs",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-toml-rs/0.1.0/index.json",
      "description": "",
      "docs_url": "/agent/latest/packages/ext-toml-rs/0.1.0/index.json#docs"
    },
    {
      "name": "ext-toml-rs",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-toml-rs/0.1.1/index.json",
      "description": "TOML parsing and serialization.",
      "docs_url": "/agent/latest/packages/ext-toml-rs/0.1.1/index.json#docs"
    },
    {
      "name": "ext-toml-rs",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-toml-rs/0.1.2/index.json",
      "description": "TOML parsing and serialization.",
      "docs_url": "/agent/latest/packages/ext-toml-rs/0.1.2/index.json#docs"
    },
    {
      "name": "ext-toml-rs",
      "version": "0.1.3",
      "url": "/agent/latest/packages/ext-toml-rs/0.1.3/index.json",
      "description": "TOML parsing and serialization.",
      "docs_url": "/agent/latest/packages/ext-toml-rs/0.1.3/index.json#docs"
    },
    {
      "name": "ext-toml-rs",
      "version": "0.1.4",
      "url": "/agent/latest/packages/ext-toml-rs/0.1.4/index.json",
      "description": "TOML parsing and serialization.",
      "docs_url": "/agent/latest/packages/ext-toml-rs/0.1.4/index.json#docs"
    },
    {
      "name": "ext-toml-rs",
      "version": "0.1.5",
      "url": "/agent/latest/packages/ext-toml-rs/0.1.5/index.json",
      "description": "TOML parsing and serialization.",
      "docs_url": "/agent/latest/packages/ext-toml-rs/0.1.5/index.json#docs"
    },
    {
      "name": "ext-tracing",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-tracing/0.1.0/index.json",
      "description": "",
      "docs_url": "/agent/latest/packages/ext-tracing/0.1.0/index.json#docs"
    },
    {
      "name": "ext-tracing",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-tracing/0.1.1/index.json",
      "description": "Trace span/event record encoding and formatting.",
      "docs_url": "/agent/latest/packages/ext-tracing/0.1.1/index.json#docs"
    },
    {
      "name": "ext-tracing",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-tracing/0.1.2/index.json",
      "description": "Trace span/event record encoding and formatting.",
      "docs_url": "/agent/latest/packages/ext-tracing/0.1.2/index.json#docs"
    },
    {
      "name": "ext-tracing",
      "version": "0.1.3",
      "url": "/agent/latest/packages/ext-tracing/0.1.3/index.json",
      "description": "Trace span/event record encoding and formatting.",
      "docs_url": "/agent/latest/packages/ext-tracing/0.1.3/index.json#docs"
    },
    {
      "name": "ext-tracing",
      "version": "0.1.4",
      "url": "/agent/latest/packages/ext-tracing/0.1.4/index.json",
      "description": "Trace span/event record encoding and formatting.",
      "docs_url": "/agent/latest/packages/ext-tracing/0.1.4/index.json#docs"
    },
    {
      "name": "ext-u64-rs",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-u64-rs/0.1.0/index.json",
      "description": "",
      "docs_url": "/agent/latest/packages/ext-u64-rs/0.1.0/index.json#docs"
    },
    {
      "name": "ext-u64-rs",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-u64-rs/0.1.1/index.json",
      "description": "Unsigned 64-bit integer utilities.",
      "docs_url": "/agent/latest/packages/ext-u64-rs/0.1.1/index.json#docs"
    },
    {
      "name": "ext-u64-rs",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-u64-rs/0.1.2/index.json",
      "description": "Unsigned 64-bit integer utilities.",
      "docs_url": "/agent/latest/packages/ext-u64-rs/0.1.2/index.json#docs"
    },
    {
      "name": "ext-u64-rs",
      "version": "0.1.3",
      "url": "/agent/latest/packages/ext-u64-rs/0.1.3/index.json",
      "description": "Unsigned 64-bit integer utilities.",
      "docs_url": "/agent/latest/packages/ext-u64-rs/0.1.3/index.json#docs"
    },
    {
      "name": "ext-u64-rs",
      "version": "0.1.4",
      "url": "/agent/latest/packages/ext-u64-rs/0.1.4/index.json",
      "description": "Unsigned 64-bit integer utilities.",
      "docs_url": "/agent/latest/packages/ext-u64-rs/0.1.4/index.json#docs"
    },
    {
      "name": "ext-unicode-rs",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-unicode-rs/0.1.0/index.json",
      "description": "",
      "docs_url": "/agent/latest/packages/ext-unicode-rs/0.1.0/index.json#docs"
    },
    {
      "name": "ext-unicode-rs",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-unicode-rs/0.1.1/index.json",
      "description": "Unicode character and string utilities.",
      "docs_url": "/agent/latest/packages/ext-unicode-rs/0.1.1/index.json#docs"
    },
    {
      "name": "ext-unicode-rs",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-unicode-rs/0.1.2/index.json",
      "description": "Unicode character and string utilities.",
      "docs_url": "/agent/latest/packages/ext-unicode-rs/0.1.2/index.json#docs"
    },
    {
      "name": "ext-unicode-rs",
      "version": "0.1.3",
      "url": "/agent/latest/packages/ext-unicode-rs/0.1.3/index.json",
      "description": "Unicode character and string utilities.",
      "docs_url": "/agent/latest/packages/ext-unicode-rs/0.1.3/index.json#docs"
    },
    {
      "name": "ext-unicode-rs",
      "version": "0.1.4",
      "url": "/agent/latest/packages/ext-unicode-rs/0.1.4/index.json",
      "description": "Unicode character and string utilities.",
      "docs_url": "/agent/latest/packages/ext-unicode-rs/0.1.4/index.json#docs"
    },
    {
      "name": "ext-unicode-rs",
      "version": "0.1.5",
      "url": "/agent/latest/packages/ext-unicode-rs/0.1.5/index.json",
      "description": "Unicode character and string utilities.",
      "docs_url": "/agent/latest/packages/ext-unicode-rs/0.1.5/index.json#docs"
    },
    {
      "name": "ext-url-rs",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-url-rs/0.1.0/index.json",
      "description": "",
      "docs_url": "/agent/latest/packages/ext-url-rs/0.1.0/index.json#docs"
    },
    {
      "name": "ext-url-rs",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-url-rs/0.1.1/index.json",
      "description": "HTTP types/parsing and URL parsing/encoding.",
      "docs_url": "/agent/latest/packages/ext-url-rs/0.1.1/index.json#docs"
    },
    {
      "name": "ext-url-rs",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-url-rs/0.1.2/index.json",
      "description": "HTTP types/parsing and URL parsing/encoding.",
      "docs_url": "/agent/latest/packages/ext-url-rs/0.1.2/index.json#docs"
    },
    {
      "name": "ext-url-rs",
      "version": "0.1.3",
      "url": "/agent/latest/packages/ext-url-rs/0.1.3/index.json",
      "description": "HTTP types/parsing and URL parsing/encoding.",
      "docs_url": "/agent/latest/packages/ext-url-rs/0.1.3/index.json#docs"
    },
    {
      "name": "ext-url-rs",
      "version": "0.1.4",
      "url": "/agent/latest/packages/ext-url-rs/0.1.4/index.json",
      "description": "HTTP types/parsing and URL parsing/encoding.",
      "docs_url": "/agent/latest/packages/ext-url-rs/0.1.4/index.json#docs"
    },
    {
      "name": "ext-uuid-rs",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-uuid-rs/0.1.0/index.json",
      "description": "",
      "docs_url": "/agent/latest/packages/ext-uuid-rs/0.1.0/index.json#docs"
    },
    {
      "name": "ext-uuid-rs",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-uuid-rs/0.1.1/index.json",
      "description": "UUID parsing and formatting.",
      "docs_url": "/agent/latest/packages/ext-uuid-rs/0.1.1/index.json#docs"
    },
    {
      "name": "ext-uuid-rs",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-uuid-rs/0.1.2/index.json",
      "description": "UUID parsing and formatting.",
      "docs_url": "/agent/latest/packages/ext-uuid-rs/0.1.2/index.json#docs"
    },
    {
      "name": "ext-uuid-rs",
      "version": "0.1.3",
      "url": "/agent/latest/packages/ext-uuid-rs/0.1.3/index.json",
      "description": "UUID parsing and formatting.",
      "docs_url": "/agent/latest/packages/ext-uuid-rs/0.1.3/index.json#docs"
    },
    {
      "name": "ext-uuid-rs",
      "version": "0.1.4",
      "url": "/agent/latest/packages/ext-uuid-rs/0.1.4/index.json",
      "description": "UUID parsing and formatting.",
      "docs_url": "/agent/latest/packages/ext-uuid-rs/0.1.4/index.json#docs"
    },
    {
      "name": "ext-walkdir-rs",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-walkdir-rs/0.1.0/index.json",
      "description": "Directory traversal helpers for OS worlds (wrap std.os.fs.walk_glob_sorted_text_v1).",
      "docs_url": "/agent/latest/packages/ext-walkdir-rs/0.1.0/index.json#docs"
    },
    {
      "name": "ext-walkdir-rs",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-walkdir-rs/0.1.1/index.json",
      "description": "Directory traversal helpers for OS worlds (wrap std.os.fs.walk_glob_sorted_text_v1).",
      "docs_url": "/agent/latest/packages/ext-walkdir-rs/0.1.1/index.json#docs"
    },
    {
      "name": "ext-walkdir-rs",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-walkdir-rs/0.1.2/index.json",
      "description": "Directory traversal helpers for OS worlds (wrap std.os.fs.walk_glob_sorted_text_v1).",
      "docs_url": "/agent/latest/packages/ext-walkdir-rs/0.1.2/index.json#docs"
    },
    {
      "name": "ext-xml-rs",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-xml-rs/0.1.0/index.json",
      "description": "",
      "docs_url": "/agent/latest/packages/ext-xml-rs/0.1.0/index.json#docs"
    },
    {
      "name": "ext-xml-rs",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-xml-rs/0.1.1/index.json",
      "description": "XML parsing and ext.data_model integration.",
      "docs_url": "/agent/latest/packages/ext-xml-rs/0.1.1/index.json#docs"
    },
    {
      "name": "ext-xml-rs",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-xml-rs/0.1.2/index.json",
      "description": "XML parsing and ext.data_model integration.",
      "docs_url": "/agent/latest/packages/ext-xml-rs/0.1.2/index.json#docs"
    },
    {
      "name": "ext-xml-rs",
      "version": "0.1.3",
      "url": "/agent/latest/packages/ext-xml-rs/0.1.3/index.json",
      "description": "XML parsing and ext.data_model integration.",
      "docs_url": "/agent/latest/packages/ext-xml-rs/0.1.3/index.json#docs"
    },
    {
      "name": "ext-xml-rs",
      "version": "0.1.4",
      "url": "/agent/latest/packages/ext-xml-rs/0.1.4/index.json",
      "description": "XML parsing and ext.data_model integration.",
      "docs_url": "/agent/latest/packages/ext-xml-rs/0.1.4/index.json#docs"
    },
    {
      "name": "ext-yaml-rs",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-yaml-rs/0.1.0/index.json",
      "description": "",
      "docs_url": "/agent/latest/packages/ext-yaml-rs/0.1.0/index.json#docs"
    },
    {
      "name": "ext-yaml-rs",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-yaml-rs/0.1.1/index.json",
      "description": "YAML parsing and serialization.",
      "docs_url": "/agent/latest/packages/ext-yaml-rs/0.1.1/index.json#docs"
    },
    {
      "name": "ext-yaml-rs",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-yaml-rs/0.1.2/index.json",
      "description": "YAML parsing and serialization.",
      "docs_url": "/agent/latest/packages/ext-yaml-rs/0.1.2/index.json#docs"
    },
    {
      "name": "ext-yaml-rs",
      "version": "0.1.3",
      "url": "/agent/latest/packages/ext-yaml-rs/0.1.3/index.json",
      "description": "YAML parsing and serialization.",
      "docs_url": "/agent/latest/packages/ext-yaml-rs/0.1.3/index.json#docs"
    },
    {
      "name": "ext-yaml-rs",
      "version": "0.1.4",
      "url": "/agent/latest/packages/ext-yaml-rs/0.1.4/index.json",
      "description": "YAML parsing and serialization.",
      "docs_url": "/agent/latest/packages/ext-yaml-rs/0.1.4/index.json#docs"
    },
    {
      "name": "ext-zlib-c",
      "version": "0.1.0",
      "url": "/agent/latest/packages/ext-zlib-c/0.1.0/index.json",
      "description": "",
      "docs_url": "/agent/latest/packages/ext-zlib-c/0.1.0/index.json#docs"
    },
    {
      "name": "ext-zlib-c",
      "version": "0.1.1",
      "url": "/agent/latest/packages/ext-zlib-c/0.1.1/index.json",
      "description": "zlib compression bindings (run-os only).",
      "docs_url": "/agent/latest/packages/ext-zlib-c/0.1.1/index.json#docs"
    },
    {
      "name": "ext-zlib-c",
      "version": "0.1.2",
      "url": "/agent/latest/packages/ext-zlib-c/0.1.2/index.json",
      "description": "zlib compression bindings (run-os only).",
      "docs_url": "/agent/latest/packages/ext-zlib-c/0.1.2/index.json#docs"
    },
    {
      "name": "ext-zlib-c",
      "version": "0.1.3",
      "url": "/agent/latest/packages/ext-zlib-c/0.1.3/index.json",
      "description": "zlib compression bindings (run-os only).",
      "docs_url": "/agent/latest/packages/ext-zlib-c/0.1.3/index.json#docs"
    },
    {
      "name": "ext-zlib-c",
      "version": "0.1.4",
      "url": "/agent/latest/packages/ext-zlib-c/0.1.4/index.json",
      "description": "zlib compression bindings (run-os only).",
      "docs_url": "/agent/latest/packages/ext-zlib-c/0.1.4/index.json#docs"
    },
    {
      "name": "ext-zlib-c",
      "version": "0.1.5",
      "url": "/agent/latest/packages/ext-zlib-c/0.1.5/index.json",
      "description": "zlib compression bindings (run-os only).",
      "docs_url": "/agent/latest/packages/ext-zlib-c/0.1.5/index.json#docs"
    }
  ]
} as const;

export const latestStdlibIndexMeta = {
  url: '/agent/latest/stdlib/index.json',
  module_count: 39,
} as const;
