/**
 * THIS FILE IS GENERATED by scripts/generate_agent_indexes.py
 * DO NOT EDIT BY HAND.
 */

export const latestSkillsIndex = {
  "schema_version": "x07.website.agent.skills_index@v1",
  "generated_from": "agent/latest/skills/*/SKILL.md",
  "items": [
    {
      "id": "x07-agent-playbook",
      "summary": "Agent-first workflow and design rails for building X07 programs with the released toolchain (no repo-only dependencies).",
      "docs_url": "/agent/latest/skills/x07-agent-playbook/SKILL.md",
      "report_schema_url": null
    },
    {
      "id": "x07-build-run",
      "summary": "Compile and run deterministic solve-world X07 programs via x07-host-runner, producing a machine-readable JSON report.",
      "docs_url": "/agent/latest/skills/x07-build-run/SKILL.md",
      "report_schema_url": "/agent/latest/schemas/x07-host-runner.report.schema.json"
    },
    {
      "id": "x07-concurrency",
      "summary": "Canonical deterministic concurrency patterns in X07 (defasync + task.* + chan.bytes.*), including the determinism constraints.",
      "docs_url": "/agent/latest/skills/x07-concurrency/SKILL.md",
      "report_schema_url": null
    },
    {
      "id": "x07-ffi-c",
      "summary": "Emit C output and a C header for embedding X07 in C/C++ via x07c --emit-c-header.",
      "docs_url": "/agent/latest/skills/x07-ffi-c/SKILL.md",
      "report_schema_url": null
    },
    {
      "id": "x07-format",
      "summary": "Canonically format X07 x07AST JSON files using x07c fmt (check/write) with a machine-readable JSON report.",
      "docs_url": "/agent/latest/skills/x07-format/SKILL.md",
      "report_schema_url": "/agent/latest/schemas/x07c.report.schema.json"
    },
    {
      "id": "x07-io-streams",
      "summary": "Canonical streaming I/O patterns in X07 using std.io / std.io.bufread and world adapters.",
      "docs_url": "/agent/latest/skills/x07-io-streams/SKILL.md",
      "report_schema_url": null
    },
    {
      "id": "x07-language-guide",
      "summary": "Canonical X07 language + stdlib reference (mirrors `x07c guide` output) for end-user skill packs.",
      "docs_url": "/agent/latest/skills/x07-language-guide/SKILL.md",
      "report_schema_url": null
    },
    {
      "id": "x07-lint-repair",
      "summary": "Lint X07 x07AST JSON and converge via deterministic quickfixes (x07c fix) or explicit JSON Patch (x07 ast apply-patch).",
      "docs_url": "/agent/latest/skills/x07-lint-repair/SKILL.md",
      "report_schema_url": "/agent/latest/schemas/x07c.report.schema.json"
    },
    {
      "id": "x07-os-run",
      "summary": "Run X07 programs in run-os / run-os-sandboxed worlds using x07-os-runner, producing machine-readable runner reports.",
      "docs_url": "/agent/latest/skills/x07-os-run/SKILL.md",
      "report_schema_url": "/agent/latest/schemas/x07-os-runner.report.schema.json"
    },
    {
      "id": "x07-package",
      "summary": "Manage X07 project dependencies and lockfiles for reproducible builds (lock, publish). Designed for autonomous agents.",
      "docs_url": "/agent/latest/skills/x07-package/SKILL.md",
      "report_schema_url": null
    },
    {
      "id": "x07-test",
      "summary": "Run project tests using the X07 test harness (x07 test), producing a machine-readable JSON report.",
      "docs_url": "/agent/latest/skills/x07-test/SKILL.md",
      "report_schema_url": "/agent/latest/schemas/x07test.schema.json"
    }
  ]
} as const;

export const latestSchemasIndex = {
  "schema_version": "x07.website.agent.schemas_index@v1",
  "generated_from": "agent/latest/schemas/*.schema.json",
  "items": [
    {
      "id": "run-os-policy.schema.json",
      "url": "/agent/latest/schemas/run-os-policy.schema.json"
    },
    {
      "id": "x07-host-runner.report.schema.json",
      "url": "/agent/latest/schemas/x07-host-runner.report.schema.json"
    },
    {
      "id": "x07-os-runner.report.schema.json",
      "url": "/agent/latest/schemas/x07-os-runner.report.schema.json"
    },
    {
      "id": "x07.native-backends.schema.json",
      "url": "/agent/latest/schemas/x07.native-backends.schema.json"
    },
    {
      "id": "x07.native-requires.schema.json",
      "url": "/agent/latest/schemas/x07.native-requires.schema.json"
    },
    {
      "id": "x07ast.schema.json",
      "url": "/agent/latest/schemas/x07ast.schema.json"
    },
    {
      "id": "x07c.report.schema.json",
      "url": "/agent/latest/schemas/x07c.report.schema.json"
    },
    {
      "id": "x07cli.specrows.schema.json",
      "url": "/agent/latest/schemas/x07cli.specrows.schema.json"
    },
    {
      "id": "x07diag.schema.json",
      "url": "/agent/latest/schemas/x07diag.schema.json"
    },
    {
      "id": "x07patch.schema.json",
      "url": "/agent/latest/schemas/x07patch.schema.json"
    },
    {
      "id": "x07test.schema.json",
      "url": "/agent/latest/schemas/x07test.schema.json"
    }
  ]
} as const;

export const latestExamplesIndex = {
  "schema_version": "x07.website.agent.examples_index@v1",
  "generated_from": "agent/latest/examples/*.x07.json",
  "items": [
    {
      "id": "01_echo",
      "purpose": "echo",
      "url": "/agent/latest/examples/01_echo.x07.json"
    },
    {
      "id": "02_length",
      "purpose": "length",
      "url": "/agent/latest/examples/02_length.x07.json"
    },
    {
      "id": "03_reverse",
      "purpose": "reverse",
      "url": "/agent/latest/examples/03_reverse.x07.json"
    },
    {
      "id": "04_sum_bytes",
      "purpose": "sum bytes",
      "url": "/agent/latest/examples/04_sum_bytes.x07.json"
    },
    {
      "id": "05_max_byte",
      "purpose": "max byte",
      "url": "/agent/latest/examples/05_max_byte.x07.json"
    },
    {
      "id": "06_count_first",
      "purpose": "count first",
      "url": "/agent/latest/examples/06_count_first.x07.json"
    },
    {
      "id": "07_first_line_len",
      "purpose": "first line len",
      "url": "/agent/latest/examples/07_first_line_len.x07.json"
    },
    {
      "id": "08_is_palindrome",
      "purpose": "is palindrome",
      "url": "/agent/latest/examples/08_is_palindrome.x07.json"
    },
    {
      "id": "09_word_count",
      "purpose": "word count",
      "url": "/agent/latest/examples/09_word_count.x07.json"
    },
    {
      "id": "10_rle_encode",
      "purpose": "rle encode",
      "url": "/agent/latest/examples/10_rle_encode.x07.json"
    },
    {
      "id": "11_data_analyzer",
      "purpose": "data analyzer",
      "url": "/agent/latest/examples/11_data_analyzer.x07.json"
    },
    {
      "id": "12_async_mapreduce",
      "purpose": "async mapreduce",
      "url": "/agent/latest/examples/12_async_mapreduce.x07.json"
    }
  ]
} as const;

export const latestStdlibIndexMeta = {
  url: '/agent/latest/stdlib/index.json',
  module_count: 39,
} as const;
